
# DEPENDENCIES #

include $(TOOLS_MAKE_LIB_DIR)/test-fixtures/c.mk
include $(TOOLS_MAKE_LIB_DIR)/test-fixtures/cpp.mk
include $(TOOLS_MAKE_LIB_DIR)/test-fixtures/fortran.mk
include $(TOOLS_MAKE_LIB_DIR)/test-fixtures/julia.mk
include $(TOOLS_MAKE_LIB_DIR)/test-fixtures/python.mk
include $(TOOLS_MAKE_LIB_DIR)/test-fixtures/r.mk


# TARGETS #

# Generate test fixtures.
#
# This target generates test fixtures across languages.

test-fixtures: test-fixtures-c test-fixtures-cpp test-fixtures-fortran test-fixtures-julia test-fixtures-python test-fixtures-r

.PHONY: test-fixtures
