#/
# @license Apache-2.0
#
# Copyright (c) 2017 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#/

# DEPENDENCIES #

include $(TOOLS_MAKE_LIB_DIR)/test-fixtures/c.mk
include $(TOOLS_MAKE_LIB_DIR)/test-fixtures/cpp.mk
include $(TOOLS_MAKE_LIB_DIR)/test-fixtures/fortran.mk
include $(TOOLS_MAKE_LIB_DIR)/test-fixtures/julia.mk
include $(TOOLS_MAKE_LIB_DIR)/test-fixtures/python.mk
include $(TOOLS_MAKE_LIB_DIR)/test-fixtures/r.mk


# TARGETS #

# Generate test fixtures.
#
# This target generates test fixtures across languages.

test-fixtures: test-fixtures-c test-fixtures-cpp test-fixtures-fortran test-fixtures-julia test-fixtures-python test-fixtures-r

.PHONY: test-fixtures
