
# DEPENDENCIES #

include $(TOOLS_MAKE_DIR)/lib/install/node.mk


# TARGETS #

# Run the install process.
#
# This target runs the project's install process.

install: install-node


.PHONY: install
