#/
# @license Apache-2.0
#
# Copyright 2017 The Stdlib Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#/

# Enable analysis [engines][1].
#
# [1]: https://docs.codeclimate.com/docs/list-of-engines
engines:
  # Analyze bash files using [shellcheck][1].
  #
  # [1]: https://github.com/koalaman/shellcheck
  shellcheck:
    enabled: true

  # Analyze JavaScript files using [ESLint][1].
  #
  # [1]:https://docs.codeclimate.com/docs/eslint
  eslint:
    enabled: true

  # Audit Node.js dependencies for security vulnerabilities using [Node Security][1].
  #
  # [1]: https://github.com/nodesecurity/nsp
  nodesecurity:
    enabled: true

  # Analyze CSS files using [CSSLint][1].
  #
  # [1]: https://docs.codeclimate.com/docs/csslint
  csslint:
    enabled: true

  # Analyze Sass files using [SCSS lint][1].
  #
  # [1]: https://github.com/ivantsepp/codeclimate-scss-lint
  scss-lint:
    enabled: false

  # Analyze Python files using [Pep8][1].
  #
  # [1]: https://www.python.org/dev/peps/pep-0008/
  pep8:
    enabled: true

  # Analyze Markdown files using [markdownlint][1].
  #
  # [1]: https://github.com/mivok/markdownlint
  markdownlint:
    enabled: false

  # Analyze Golang files using [golint][1].
  #
  # [1]: https://github.com/golang/lint
  golint:
    enabled: true
    config:
      min_confidence: 0.8

  # Audit Golang files for suspicious constructs and potential bugs using [govet][1].
  #
  # [1]: https://golang.org/cmd/vet
  govet:
    enabled: true

  # Ensure Golang files adhere to the official style using [gofmt][1].
  #
  # [1]: https://golang.org/cmd/gofmt
  gofmt:
    enabled: true

  # Analyze source files for code similarity using [duplication][1].
  #
  # [1]: https://docs.codeclimate.com/v1.0/docs/duplication
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 40
        python:
          mass_threshold: 32

  # Analyze source files for annotations using [FIXME][1].
  #
  # [1]: https://docs.codeclimate.com/v1.0/docs/fixme
  fixme:
    enabled: false
    config:
      strings:
        - TODO
        - FIXME
        - WARNING
        - HACK
        - NOTE
        - OPTIMIZE
        - BUG
        - XXX

  # Disable all other engines:
  brakeman:
    enabled: false
  bundler-audit:
    enabled: false
  coffeelint:
    enabled: false
  phpcodesniffer:
    enabled: false
  phpmd:
    enabled: false
  radon:
    enabled: false
  rubocop:
    enabled: false
  watson:
    enabled: false
  foodcritic:
    enabled: false
  haxe-checkstyle:
    enabled: false
  hlint:
    enabled: false
  phan:
    enabled: false
  reek:
    enabled: false
  rubymotion:
    enabled: false
  tailor:
    enabled: false
  vint:
    enabled: false
  gnu-complexity:
    enabled: false


# Specify which files/folders should have [ratings][1].
#
# [1]: https://docs.codeclimate.com/docs/ratings
ratings:
  paths:
    - "lib/**/*"
    - "test/**/*"
    - "examples/**/*"
    - "benchmark/**/*"
    - "bin/**/*"
    - "tools/**/*"
    - "scripts/**/*"
    - "**.sh"
    - "**.js"
    - "**.css"
    # - "**.scss"
    # - "**.md"
    - "**.py"
    - "**.go"


# Specify which files/folders should be [ignored][1] when performing analyses.
#
# [1]: https://docs.codeclimate.com/docs/excluding-files-and-folders
exclude_paths:
  - "node_modules/"
  - "reports/"
  - "build/"
  - "**/build/"
  - "dist/"
  - "tmp/"
  - "**/tmp/"
