#!/usr/bin/env bash
#
# Check whether GNU make is installed.
#
# Usage: check_gnu_make
#

# VARIABLES #

# Find GNU Make:
GNU_MAKE=$(command -v make 2>/dev/null)


# FUNCTIONS #

# Prints usage information.
usage() {
	echo '' >&2
	echo 'Usage: check_gnu_make' >&2
	echo '' >&2
}

# MAIN #

if [[ -x "${GNU_MAKE}" ]] && "${GNU_MAKE}" --version >/dev/null; then
	echo 'GNU make is installed.' >&2
	exit 0
else
	echo 'ERROR: missing dependency. Please install GNU make (https://www.gnu.org/software/make). Once installed, run the command again.' >&2
	exit 1
fi

# TODO: check for minimum version
