#!/usr/bin/env bash
#
# Check whether fetch is installed.
#
# Usage: check_fetch
#

# VARIABLES #

# Find fetch:
FETCH=$(command -v fetch 2>/dev/null)


# FUNCTIONS #

# Prints usage information.
usage() {
	echo '' >&2
	echo 'Usage: check_fetch' >&2
	echo '' >&2
}

# MAIN #

if [[ -x "${FETCH}" ]] && "${FETCH}" --version >/dev/null; then
	echo 'fetch is installed.' >&2
	exit 0
else
	echo 'ERROR: missing dependency. Please install fetch (http://www.freebsd.org/cgi/man.cgi?fetch%281%29). Once installed, run the command again.' >&2
	exit 1
fi

# TODO: check for minimum version
