#!/usr/bin/env bash
#
# Check whether g++ is installed.
#
# Usage: check_gxx
#

# VARIABLES #

# Find g++:
GXX=$(command -v g++ 2>/dev/null)


# FUNCTIONS #

# Prints usage information.
usage() {
	echo '' >&2
	echo 'Usage: check_gxx' >&2
	echo '' >&2
}

# MAIN #

if [[ -x "${GXX}" ]] && "${GXX}" --version >/dev/null; then
	echo 'g++ is installed.' >&2
	exit 0
else
	echo 'ERROR: missing dependency. Please download g++ version >= 4.8 (http://gcc.gnu.org/). Once installed, run the command again.' >&2
	exit 1
fi

# TODO: check for minimum version
