#!/usr/bin/env bash
#
# Check whether CMake is installed.
#
# Usage: check_cmake
#

# VARIABLES #

# Find CMake:
CMAKE=$(command -v cmake 2>/dev/null)


# FUNCTIONS #

# Prints usage information.
usage() {
	echo '' >&2
	echo 'Usage: check_cmake' >&2
	echo '' >&2
}

# MAIN #

if [[ -x "${CMAKE}" ]] && "${CMAKE}" --version >/dev/null; then
	echo 'CMake is installed.' >&2
	exit 0
else
	echo 'ERROR: missing dependency. Please download CMake version >= 3.4.3 (https://cmake.org/). Once installed, run the command again.' >&2
	exit 1
fi

# TODO: check for minimum version
