#!/usr/bin/env bash
#
# Check whether lintr is installed.
#
# Usage: check_lintr
#

# VARIABLES #

# Find Rscript:
RSCRIPT=$(command -v rscript 2>/dev/null)


# FUNCTIONS #

# Prints usage information.
usage() {
	echo '' >&2
	echo 'Usage: check_lintr' >&2
	echo '' >&2
}

# MAIN #

if [[ -x "${RSCRIPT}" ]] && "${RSCRIPT}" -e 'packageVersion("lintr")' >/dev/null; then
	echo 'lintr is installed.' >&2
	exit 0
else
	echo 'ERROR: missing dependency. Please download lintr version >= 1.0.0 (https://github.com/jimhester/lintr). Once installed, run the command again.' >&2
	exit 1
fi

# TODO: check for minimum version
