#!/usr/bin/env bash
#
# @license Apache-2.0
#
# Copyright (c) 2017 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Check whether lintr is installed.
#
# Usage: check_lintr
#

# VARIABLES #

# Find Rscript:
RSCRIPT=$(command -v Rscript 2>/dev/null)


# MAIN #

if [[ -x "${RSCRIPT}" ]] && "${RSCRIPT}" -e 'packageVersion("lintr")' &>/dev/null; then
	echo 'lintr is installed.' >&2
	exit 0
else
	echo 'ERROR: missing dependency. Please download lintr version >= 1.0.0 (https://github.com/jimhester/lintr). Once installed, run the command again.' >&2
	exit 1
fi

# TODO: check for minimum version
