#!/usr/bin/env bash
#
# @license Apache-2.0
#
# Copyright (c) 2017 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Check whether Python is installed.
#
# Usage: check_python
#

# VARIABLES #

# Find python:
PYTHON=$(command -v python 2>/dev/null)


# FUNCTIONS #

# Prints usage information.
usage() {
	echo '' >&2
	echo 'Usage: check_python' >&2
	echo '' >&2
}

# MAIN #

if [[ -x "${PYTHON}" ]] && "${PYTHON}" --version >/dev/null; then
	echo 'Python is installed.' >&2
	exit 0
else
	echo 'ERROR: missing dependency. Please download Python version >=2.7 (https://www.python.org/). Once installed, run the command again.' >&2
	exit 1
fi

# TODO: check for minimum version
