#!/usr/bin/env bash
#
# Check whether Julia is installed.
#
# Usage: check_julia
#

# VARIABLES #

# Find Julia:
JULIA=$(command -v julia 2>/dev/null)


# FUNCTIONS #

# Prints usage information.
usage() {
	echo '' >&2
	echo 'Usage: check_julia' >&2
	echo '' >&2
}

# MAIN #

if [[ -x "${JULIA}" ]] && "${JULIA}" --version >/dev/null; then
	echo 'Julia is installed.' >&2
	exit 0
else
	echo 'ERROR: missing dependency. Please download Julia version >= 0.5 (http://julialang.org/). Once installed, run the command again.' >&2
	exit 1
fi

# TODO: check for minimum version
