#!/usr/bin/env bash
#
# Check whether pandoc is installed.
#
# Usage: check_pandoc
#

# VARIABLES #

# Find pandoc:
PANDOC=$(command -v pandoc 2>/dev/null)


# FUNCTIONS #

# Prints usage information.
usage() {
	echo '' >&2
	echo 'Usage: check_pandoc' >&2
	echo '' >&2
}

# MAIN #

if [[ -x "${PANDOC}" ]] && "${PANDOC}" -v >/dev/null; then
	echo 'pandoc is installed.' >&2
	exit 0
else
	echo 'ERROR: missing dependency. Please download pandoc version >= 1.18 (http://pandoc.org/). Once installed, run the command again.' >&2
	exit 1
fi

# TODO: check for minimum version
