#!/usr/bin/env bash
#
# Check whether pydocstyle is installed.
#
# Usage: check_pydocstyle
#

# VARIABLES #

# Find pydocstyle:
PYDOCSTYLE=$(command -v pydocstyle 2>/dev/null)


# FUNCTIONS #

# Prints usage information.
usage() {
	echo '' >&2
	echo 'Usage: check_pydocstyle' >&2
	echo '' >&2
}

# MAIN #

if [[ -x "${PYDOCSTYLE}" ]] && "${PYDOCSTYLE}" --version >/dev/null; then
	echo 'pydocstyle is installed.' >&2
	exit 0
else
	echo 'ERROR: missing dependency. Please download pydocstyle (https://github.com/PyCQA/pydocstyle). Once installed, run the command again.' >&2
	exit 1
fi

# TODO: check for minimum version
