#!/usr/bin/env bash
#
# Check whether make is installed.
#
# Usage: check_make
#

# VARIABLES #

# Find Make:
MAKE=$(command -v make 2>/dev/null)


# FUNCTIONS #

# Prints usage information.
usage() {
	echo '' >&2
	echo 'Usage: check_make' >&2
	echo '' >&2
}

# MAIN #

if [[ -x "${MAKE}" ]] && "${MAKE}" --version >/dev/null; then
	echo 'make is installed.' >&2
	exit 0
else
	echo 'ERROR: missing dependency. Please install make (https://www.gnu.org/software/make). Once installed, run the command again.' >&2
	exit 1
fi

# TODO: check for minimum version
