#!/usr/bin/env bash
#
# Check whether curl is installed.
#
# Usage: check_curl
#

# VARIABLES #

# Find curl:
CURL=$(command -v curl 2>/dev/null)


# FUNCTIONS #

# Prints usage information.
usage() {
	echo '' >&2
	echo 'Usage: check_curl' >&2
	echo '' >&2
}

# MAIN #

if [[ -x "${CURL}" ]] && "${CURL}" --version >/dev/null; then
	echo 'curl is installed.' >&2
	exit 0
else
	echo 'ERROR: missing dependency. Please install curl (http://curl.haxx.se/). Once installed, run the command again.' >&2
	exit 1
fi

# TODO: check for minimum version
