#!/usr/bin/env bash
#
# Check whether R is installed.
#
# Usage: check_r
#

# VARIABLES #

# Find R:
R=$(command -v r 2>/dev/null)


# FUNCTIONS #

# Prints usage information.
usage() {
	echo '' >&2
	echo 'Usage: check_r' >&2
	echo '' >&2
}

# MAIN #

if [[ -x "${R}" ]] && "${R}" --version >/dev/null; then
	echo 'R is installed.' >&2
	exit 0
else
	echo 'ERROR: missing dependency. Please download R version >= 3.0.0 (https://www.r-project.org/). Once installed, run the command again.' >&2
	exit 1
fi

# TODO: check for minimum version
