#!/usr/bin/env bash
#
# Check whether gfortran is installed.
#
# Usage: check_gfortran
#

# VARIABLES #

# Find gfortran:
GFORTRAN=$(command -v gfortran 2>/dev/null)


# FUNCTIONS #

# Prints usage information.
usage() {
	echo '' >&2
	echo 'Usage: check_gfortran' >&2
	echo '' >&2
}

# MAIN #

if [[ -x "${GFORTRAN}" ]] && "${GFORTRAN}" --version >/dev/null; then
	echo 'gfortran is installed.' >&2
	exit 0
else
	echo 'ERROR: missing dependency. Please download gfortran version >= 4.8 (https://gcc.gnu.org/fortran/). Once installed, run the command again.' >&2
	exit 1
fi

# TODO: check for minimum version
