#!/usr/bin/env bash
#
# Check whether pycodestyle is installed.
#
# Usage: check_pycodestyle
#

# VARIABLES #

# Find pycodestyle:
PYCODESTYLE=$(command -v pycodestyle 2>/dev/null)


# FUNCTIONS #

# Prints usage information.
usage() {
	echo '' >&2
	echo 'Usage: check_pycodestyle' >&2
	echo '' >&2
}

# MAIN #

if [[ -x "${PYCODESTYLE}" ]] && "${PYCODESTYLE}" --version >/dev/null; then
	echo 'pycodestyle is installed.' >&2
	exit 0
else
	echo 'ERROR: missing dependency. Please download pycodestyle (https://github.com/PyCQA/pycodestyle). Once installed, run the command again.' >&2
	exit 1
fi

# TODO: check for minimum version
