#!/usr/bin/env node

/**
* @license Apache-2.0
*
* Copyright (c) 2019 The Stdlib Authors.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*    http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/* eslint-disable no-sync */

'use strict';

// MODULES //

var path = require( 'path' );
var fs = require( 'fs' );
var logger = require( 'debug' );


// VARIABLES //

var debug = logger( 'stdlib:pre-uninstall' );

// Resolve the root project directory (WARNING: this is fragile and likely needs to be updated should this file move!):
var ROOT_DIR = path.resolve( __dirname, '..', '..' );

// Resolve the project package directory:
var PKG_DIR = path.join( ROOT_DIR, 'lib', 'node_modules', '@stdlib' );

// Resolve the post-install meta data file:
var META_FILE = path.join( ROOT_DIR, '.postinstall.json' );


// MAIN //

/**
* Main execution sequence.
*
* @private
*/
function main() {
	var action;
	var meta;
	var odir;
	var ndir;
	var p;
	var i;

	debug( 'Root directory: %s', ROOT_DIR );
	debug( 'Package directory: %s', PKG_DIR );

	debug( 'Reading meta data...' );
	meta = require( META_FILE ); // eslint-disable-line stdlib/no-dynamic-require

	debug( 'Reverting changes...' );
	for ( i = meta.length-1; i >= 0; i-- ) { // NOTE: reverting changes in reverse order!!!
		action = meta[ i ][ 0 ];
		if ( action === 'move' ) {
			odir = meta[ i ][ 1 ];
			ndir = meta[ i ][ 2 ];

			debug( 'Moving: %s...', ndir );
			fs.renameSync( ndir, odir );
		} else if ( action === 'link' ) {
			p = meta[ i ][ 2 ];

			debug( 'Deleting: %s...', p );
			fs.unlinkSync( p );
		} else if ( action === 'create' ) {
			p = meta[ i ][ 1 ];

			debug( 'Deleting: %s...', p );
			fs.unlinkSync( p );
		}
	}
	debug( 'Finished reverting changes.' );
}

main();
