#!/usr/bin/env node
/*
* Script to print the Node.js directory path.
*/
'use strict';

// MODULES //

var resolve = require( 'path' ).resolve;
var isWindows = require( '@stdlib/assert/is-windows' );
var dirname = require( '@stdlib/utils/dirname' );


// MAIN //

/**
* Finds the Node.js directory path.
*
* ## Notes
*
* * We resolve the directory based on the absolute path of the executable which started the Node.js process (e.g., '/usr/local/bin/node').
*
* @private
* @returns {string} directory path
*/
function main() {
	if ( isWindows ) {
		return dirname( process.execPath );
	}
	return resolve( process.execPath, '..', '..' );
} // end FUNCTION main()

console.log( main() );
