#!/usr/bin/env node

/**
* @license Apache-2.0
*
* Copyright (c) 2017 The Stdlib Authors.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*    http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/*
* Script to print the Node.js directory path.
*/
'use strict';

// MODULES //

var resolve = require( 'path' ).resolve;
var isWindows = require( '@stdlib/assert/is-windows' );
var dirname = require( '@stdlib/utils/dirname' );


// MAIN //

/**
* Finds the Node.js directory path.
*
* ## Notes
*
* -   We resolve the directory based on the absolute path of the executable which started the Node.js process (e.g., '/usr/local/bin/node').
*
* @private
* @returns {string} directory path
*/
function main() {
	if ( isWindows ) {
		return dirname( process.execPath );
	}
	return resolve( process.execPath, '..', '..' );
}

console.log( main() );
