#!/usr/bin/env bash
#
# @license Apache-2.0
#
# Copyright (c) 2023 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Finds top-level namespace packages.


# VARIABLES #

# Determine root directory:
root_dir="$(git rev-parse --show-toplevel)"

# Define the project source code directory:
base_dir="${root_dir}/lib/node_modules"


# FUNCTIONS #

# Finds top-level namespace packages.
main() {
	local pkgs

	pkgs=$(find "${base_dir}" -mindepth 2 -maxdepth 2 -type d | sort | sed "s%^${base_dir}\\/%%");
	echo "${pkgs}"
}

# Run main:
main
