
# DEPENDENCIES #

include $(TOOLS_MAKE_LIB_DIR)/tools-test/javascript.mk


# TARGETS #

# Run unit tests.
#
# This target runs unit tests.

tools-test: tools-test-javascript

.PHONY: tools-test


# Generate a test summary.
#
# This target runs unit tests and aggregates TAP output as a test summary.

tools-test-summary: tools-test-javascript-summary

.PHONY: tools-test-summary
