#!/usr/bin/env bash
#
# @license Apache-2.0
#
# Copyright (c) 2017 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Script to generate a coverage report name when using `istanbul` for instrumenting JavaScript source files.
#
# This script is called with the following arguments:
#
# * `$1` - base directory containing instrumented source code
# * `$2` - test directory
# * `$3` - coverage report output directory


# VARIABLES #

# Base directory:
base="$1"

# Test directory:
testdir="$2"

# Output directory:
output="$3"


# FUNCTIONS #

# Main execution sequence.
main() {
	local path
	local slug

	# Remove the base path from the directory path (using POSIX shell variable expansion):
	path="${testdir#${base}/}"

	# Slugify the path (basic algorithm):
	slug=$(echo "${path}" | sed -e 's/[^[:alnum:]]/_/g' | tr -s '-' | tr '[:upper:]' '[:lower:]')

	# Generate a filename:
	echo "${output}/coverage${slug}.json"

	exit 0
}

# Run main:
main
