#!/usr/bin/env node

/**
* @license Apache-2.0
*
* Copyright (c) 2017 The Stdlib Authors.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*    http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/*
* Script to determine a compatible npm version range based on the current Node.js runtime.
*
* -   Older versions of Node (>=0.10.0 <= 0.12.x) require an updated npm client to handle scoped packages, but should not use npm versions `>=4.0.0`, as more recent npm versions drop explicit backward compatibility support.
* -   Older versions of Node (<=5.x) do not have full ES2015/ES6 support.
*/
'use strict';

// VARIABLES //

var NODE_VERSION = process.versions.node;


// FUNCTIONS //

/**
* Returns a compatible npm version range based on the current Node.js runtime.
*
* @private
* @returns {string} npm version range
*/
function version() {
	var major;
	var parts;

	parts = NODE_VERSION.split( '.' );
	major = parseInt( parts[ 0 ], 10 );
	if ( major <= 3 ) {
		return '>2.7.0 <4.0.0';
	}
	if ( major <= 5 ) {
		return '>2.7.0 <6.0.0';
	}
	if ( major <= 10 ) {
		return '>2.7.0 <7.0.0';
	}
	return '>2.7.0';
}


// MAIN //

console.log( version() ); // eslint-disable-line no-console
