
# DEPENDENCIES #

include $(TOOLS_MAKE_DIR)/lib/docs/jsdoc.mk


# TARGETS #

# Generate documentation.
#
# This target runs tasks to generate documentation.

docs: docs-jsdoc


# Remove generated documentation.
#
# This target cleans generated documentation by removing it entirely.

clean-docs: clean-jsdoc


.PHONY: docs clean-docs
