
# DEPENDENCIES #

include $(TOOLS_MAKE_LIB_DIR)/docs/src.mk


# TARGETS #

# Generate documentation.
#
# This target runs tasks to generate documentation.

docs: src-docs

.PHONY: docs


# Remove generated documentation.
#
# This target cleans generated documentation by removing it entirely.

clean-docs: clean-src-docs

.PHONY: clean-docs
