#!/usr/bin/env bash
#
# A git hook called by `git push` after it has checked the remote status, but before anything has been pushed. If this script exits with a non-zero status, nothing will be pushed.
#
# This hook is called with the following parameters:
#
# * `$1` - name of the remote to which the push is being done
# * `$2` - URL to which the push is being done
#
# If pushing without using a named remote, these arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to `stdin` in the form:
#
# ``` text
# <local ref> <local sha1> <remote ref> <remote sha1>
# ```


# VARIABLES #

remote="$1"
url="$2"

# Define the command to run tests:
export GIT_HOOK_TEST='make test'

# Determine the current branch:
export GIT_CURRENT_BRANCH="$(git name-rev --name-only HEAD)"


# FUNCTIONS #

# Defines an error handler.
#
# $1 - error status
on_error() {
	cleanup
	exit "$1"
}

# Runs clean-up tasks.
cleanup() {
	echo '' >&2
}

# Checks if commits exist to push, as `git push` will execute regardless of whether commits exist to push or not.
has_commits() {
	echo 'Checking for commits to push...' >&2
	local commits="$(git log origin/${GIT_CURRENT_BRANCH}..${GIT_CURRENT_BRANCH} --oneline)"
	if [[ -z "$commits" ]]; then
	    return 1
	fi
	return 0
}

# Runs tests.
run_tests() {
	echo 'Running tests...' >&2
	"$(${GIT_HOOK_TEST})"
	if [[ "$?" -ne 0 ]]; then
		echo '' >&2
        echo "${GIT_HOOK_TEST} failed." >&2
        return 1
    fi
    echo '' >&2
    echo 'Tests passed.' >&2
    return 0
}

# Main execution sequence.
main() {
	has_commits
	if [[ "$?" -ne 0 ]]; then
		on_error 1
	fi
	run_tests
	if [[ "$?" -ne 0 ]]; then
		on_error 1
	fi
	cleanup
	exit 0
}

# Run main:
main
