#/
# @license Apache-2.0
#
# Copyright (c) 2026 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#/

# VARIABLES #

# Define the path to the remark configuration file:
REMARK_INCLUDES_CONF ?= $(CONFIG_DIR)/remark/.remarkrc.js

# Define the path to the remark ignore file:
REMARK_INCLUDES_IGNORE ?= $(ROOT_DIR)/.remarkignore

# Define the path to a plugin which inserts content from external Markdown files:
REMARK_INCLUDES_PLUGIN ?= $(TOOLS_PKGS_DIR)/remark/plugins/remark-includes
REMARK_INCLUDES_PLUGIN_SETTINGS ?=
REMARK_INCLUDES_PLUGIN_FLAGS ?= --use $(REMARK_INCLUDES_PLUGIN)=$(REMARK_INCLUDES_PLUGIN_SETTINGS)

# Define command-line options when invoking the remark executable:
REMARK_INCLUDES_FLAGS ?= \
	--ext $(MARKDOWN_FILENAME_EXT) \
	--rc-path $(REMARK_INCLUDES_CONF) \
	--ignore-path $(REMARK_INCLUDES_IGNORE)

# Define the remark output option:
REMARK_INCLUDES_OUTPUT_FLAG ?= --output


# RULES #

#/
# Resolves Markdown include directives by inserting content from external Markdown files.
#
# ## Notes
#
# -   This rule is useful when wanting to glob for Markdown files (e.g., process all Markdown files for a particular package).
# -   In order to resolve includes, a Markdown file must contain include comment directives.
# -   This recipe should be run before other Markdown processing recipes (e.g., equations) since included content may contain additional directives.
#
# @param {string} [MARKDOWN_FILTER] - file path pattern (e.g., `.*/math/base/special/.*`)
# @param {string} [MARKDOWN_PATTERN] - filename pattern (e.g., `*.md`)
#
# @example
# make markdown-includes
#
# @example
# make markdown-includes MARKDOWN_PATTERN='README.md' MARKDOWN_FILTER='.*/math/base/special/.*'
#/
markdown-includes: $(NODE_MODULES)
	$(QUIET) $(FIND_MARKDOWN_CMD) | grep '^[\/]\|^[a-zA-Z]:[/\]' | while read -r file; do \
		echo ""; \
		echo "Processing file: $$file"; \
		"$(REMARK)" \
			$$file \
			$(REMARK_INCLUDES_FLAGS) \
			$(REMARK_INCLUDES_PLUGIN_FLAGS) \
			$(REMARK_INCLUDES_OUTPUT_FLAG) || exit 1; \
	done

.PHONY: markdown-includes

#/
# Resolves Markdown include directives for a specified list of files.
#
# ## Notes
#
# -   This rule is useful when wanting to process a list of Markdown files generated by some other command (e.g., a list of changed Markdown files obtained via `git diff`).
# -   In order to resolve includes, a Markdown file must contain include comment directives.
#
# @param {string} FILES - list of files
#
# @example
# make markdown-includes-files FILES='/foo/foo.md /foo/bar.md'
#/
markdown-includes-files: $(NODE_MODULES)
	$(QUIET) for file in $(FILES); do \
		echo ""; \
		echo "Processing file: $$file"; \
		"$(REMARK)" \
			$$file \
			$(REMARK_INCLUDES_FLAGS) \
			$(REMARK_INCLUDES_PLUGIN_FLAGS) \
			$(REMARK_INCLUDES_OUTPUT_FLAG) || exit 1; \
	done

.PHONY: markdown-includes-files
