
# VARIABLES #

# Define a generic filename pattern:
FILES_PATTERN ?= *.*

# Define a generic filepath pattern:
FILES_FILTER ?= .*/.*

# Define a filename pattern for source files:
SOURCES_PATTERN ?= *.js

# Define a filepath pattern for source files:
SOURCES_FILTER ?= .*/.*

# Define a filename pattern for test files:
TESTS_PATTERN ?= test*.js

# Define a filepath pattern for test files:
TESTS_FILTER ?= .*/.*

# Define a filename pattern for test fixtures:
TESTS_FIXTURES_PATTERN ?= *.*

# Define a filepath pattern for test fixture files:
TESTS_FIXTURES_FILTER ?= .*/.*

# Define a filename pattern for example files:
EXAMPLES_PATTERN ?= *.js

# Define a filepath pattern for example files:
EXAMPLES_FILTER ?= .*/.*


# DEPENDENCIES #

include $(TOOLS_MAKE_DIR)/lib/find/files.mk
include $(TOOLS_MAKE_DIR)/lib/find/sources.mk
include $(TOOLS_MAKE_DIR)/lib/find/tests.mk
include $(TOOLS_MAKE_DIR)/lib/find/tests-fixtures.mk
include $(TOOLS_MAKE_DIR)/lib/find/examples.mk
