#!/usr/bin/env bash
#
# @license Apache-2.0
#
# Copyright (c) 2024 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Script to remove related packages sections from README.md files.
#
# Usage: remove_related_packages file1 [file2 file3 ...]
#
# Arguments:
#
#   file1       File path.
#   file2       File path.
#   file3       File path.

# shellcheck disable=SC2068

# Ensure that the exit status of pipelines is non-zero in the event that at least one of the commands in a pipeline fails:
set -o pipefail

for file in ${@}; do
	if [[ $file == *README.md ]]; then
		awk '
		BEGIN { print_mode = 1; in_related = 0; in_related_links = 0 }
		/<section class="related">/ {
			print; print ""; print "</section>";
			in_related = 1; print_mode = 0; next
		}
		/<\/section>/ {
			if (in_related) { in_related = 0; print_mode = 1 }
			else { print }
			next
		}
		/<!-- <related-links> -->/ {
			print; print ""; print "<!-- </related-links> -->";
			in_related_links = 1; print_mode = 0; next
		}
		/<!-- <\/related-links> -->/ {
			if (in_related_links) { in_related_links = 0; print_mode = 1 }
			else { print }
			next
		}
		{ if (print_mode == 1) print }
		' "$file" > "${file}.tmp" && mv "${file}.tmp" "$file"
	fi
done

echo "All files processed successfully."
