
# DEPENDENCIES #

include $(TOOLS_MAKE_LIB_DIR)/tools-test-cov/javascript.mk


# TARGETS #

# Run units and generate a test coverage report.
#
# This target instruments source code, runs unit tests, and outputs a test coverage report.

tools-test-cov: tools-test-javascript-cov

.PHONY: tools-test-cov
