#!/usr/bin/env bash
#
# Prints the number of additions per day.
#
# <month> <day> <year> <additions>

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to generate commit short stats:
shortstats="${root}/tools/git/scripts/shortstats"

# * `shortstats`
#   - Get summary statistics for each commit.
# * `awk '{}'`
#   - Tabulate the daily totals.
# * `sort -k1n -k2M`
#   - Sort the year numerically and sort the second key as a month.
# * `awk '{}'`
#   - Format the output.
"${shortstats}" | awk '
{
	day = $5 OFS $2 OFS $3

	# Update daily totals:
	lines[day] += $9
}
END {
	for (day in lines) {
		print day OFS lines[day]
	}
}
' | sort -k1n -k2M | awk '{print $2 OFS $3 OFS $1 OFS $4}'
