#!/usr/bin/env bash
#
# Prints the number of additions per weekday.

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to generate commit short stats:
shortstats="${root}/tools/git/scripts/shortstats"

# * `shortstats`
#   - Get summary statistics for each commit.
# * `awk '{}'`
#   - Extract the commit timestamp and number of additions.
# * `perl -pe ''`
#   - Convert each Unix timestamp to a date string.
# * `awk '{}'`
#   - Tabulate the weekday totals.
"${shortstats}" | awk '{print $1 OFS $5}' | perl -pe 's/(\d+)/localtime($1)/e' | awk '
BEGIN {
	split("Mon Tue Wed Thu Fri Sat Sun", days);
}
{
	lines[$1] += $6
}
END {
	for (i = 1; i <= 7; i++) {
		print days[i] OFS lines[days[i]]
	}
}'
