#!/usr/bin/env bash
#
# Prints the number of additions per year.
#
# <year> <additions>

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to generate commit short stats:
shortstats="${root}/tools/git/scripts/shortstats"

# * `shortstats`
#   - Get summary statistics for each commit.
# * `awk '{}'`
#   - Tabulate the yearly totals.
# * `sort -k1n`
#   - Sort the year numerically.
"${shortstats}" | awk '
{
	lines[$5] += $9
}
END {
	for (yr in lines) {
		print yr OFS lines[yr]
	}
}' | sort -k1n
