#!/usr/bin/env bash
#
# @license Apache-2.0
#
# Copyright (c) 2017 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Prints the number of files changed per weekday per author.
#
# <weekday> <author_first_name> <author_last_name> <files_changed>

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to generate commit short stats:
shortstats="${root}/tools/git/scripts/shortstats"

# * `shortstats`
#   - Get summary statistics for each commit.
# * `awk '{}'`
#   - Tabulate the weekday totals.
"${shortstats}" | awk '
{
	lines[$1,$6,$7] += $8
}
END {
	for (k in lines) {
		split(k, keys, SUBSEP)
		day = keys[1]
		name = keys[2] OFS keys[3]
		if (day == "Mon") {
			mon[name] = lines[k]
		} else if (day == "Tue") {
			tue[name] = lines[k]
		} else if (day == "Wed") {
			wed[name] = lines[k]
		} else if (day == "Thu") {
			thu[name] = lines[k]
		} else if (day == "Fri") {
			fri[name] = lines[k]
		} else if (day == "Sat") {
			sat[name] = lines[k]
		} else if (day == "Sun") {
			sun[name] = lines[k]
		}
	}
	for (name in mon) {
		print "Mon" OFS name OFS mon[name]
	}
	for (name in tue) {
		print "Tue" OFS name OFS tue[name]
	}
	for (name in wed) {
		print "Wed" OFS name OFS wed[name]
	}
	for (name in thu) {
		print "Thu" OFS name OFS thu[name]
	}
	for (name in fri) {
		print "Fri" OFS name OFS fri[name]
	}
	for (name in sat) {
		print "Sat" OFS name OFS sat[name]
	}
	for (name in sun) {
		print "Sun" OFS name OFS sun[name]
	}
}'
