#!/usr/bin/env bash
#
# @license Apache-2.0
#
# Copyright (c) 2017 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Prints the number of authors per day.
#
# <weekday> <month> <day> <year> <number_of_authors>

# * `git log`
#   - Show logs.
# * `awk '{}'`
#   - Compute number of authors per day.
# * `sort -k1n -k2M`
#   - Sort the year numerically and sort the second key as a month.
# * `awk '{}'`
#   - Format the output.
git log --format=format:"%ad %aN" --date=format:"%b %d %Y" --use-mailmap | awk '
{
	day = $3 OFS $1 OFS $2
	name = $4 $5
	key = day SUBSEP name
	if (key in lines) {
		next
	}
	lines[day,name] = 1
	counts[day] += 1
}

END {
	for (day in counts) {
		print day OFS counts[day]
	}
}
'  | sort -k1n -k2M | awk '{print $2 OFS $3 OFS $1 OFS $4}'
