#!/usr/bin/env bash
#
# Prints the number of authors per month.
#
# <year> <number_of_authors>

# * `git log`
#   - Show logs.
# * `awk '{}'`
#   - Compute number of authors per year.
# * `sort -n`
#   - Sort in numerical order.
git log --format=format:"%ad %aN" --date=format:"%Y" --use-mailmap | awk '
{
	name = $2 $3
	key = $1 SUBSEP name
	if (key in lines) {
		next
	}
	lines[$1,name] = 1
	counts[$1] += 1
}

END {
	for (yr in counts) {
		print yr OFS counts[yr]
	}
}
'  | sort -n
