#!/usr/bin/env bash
#
# Prints the number of authors per month.
#
# <month> <year> <number_of_authors>

# * `git log`
#   - Show logs.
# * `awk '{}'`
#   - Compute number of authors per month.
# * `sort -k1n -k2M`
#   - Sort the year numerically and sort the second key as a month.
git log --format=format:"%ad %aN" --date=format:"%b %Y" --use-mailmap | awk '
{
	mon = $1 OFS $2
	name = $3 $4
	key = mon SUBSEP name
	if (key in lines) {
		next
	}
	lines[mon,name] = 1
	counts[mon] += 1
}

END {
	for (mon in counts) {
		print mon OFS counts[mon]
	}
}
'  | sort -k2n -k1M
