#!/usr/bin/env bash
#
# Prints the summary statistics per month per author.

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to generate commit short stats:
shortstats="${root}/tools/git/scripts/shortstats"

# * `shortstats`
#   - Get summary statistics for each commit.
# * `awk '{}'`
#   - Tabulate the monthly totals.
# * `sort -k1n -k2M`
#   - Sort the year numerically and sort the second key as a month.
# * `awk '{}'`
#   - Format the output.
"${shortstats}" | awk '
{
	mon = $5 OFS $2

	# Update monthly totals per author:
	commits[mon,$6,$7] += 1
	files[mon,$6,$7] += $8
	additions[mon,$6,$7] += $9
	deletions[mon,$6,$7] += $10
}
END {
	for (k in commits) {
		split(k, keys, SUBSEP)
		print keys[1] OFS keys[2] OFS keys[3] OFS commits[k] OFS files[k] OFS additions[k] OFS deletions[k]
	}
}
' | sort -k1n -k2M | awk '{print $2 OFS $1 OFS $3 OFS $4 OFS $5 OFS $6 OFS $7 OFS $8 OFS $9}'
