#!/usr/bin/env bash
#
# @license Apache-2.0
#
# Copyright (c) 2017 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Prints the mean commit interval per author.
#
# <author_first_name> <author_last_name> <avg_interval>

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to compute commit intervals per author:
commit_intervals="${root}/tools/git/scripts/author_commit_intervals"

# * `commit_intervals`
#   - Compute commit intervals.
# * `awk '{}'`
#   - Compute averages.
# * `sort -k3n`
#   - Sort in numeric order based on average interval.
"${commit_intervals}" | awk '
{
	name = $2 OFS $3
	intervals[name] += $1
	N[name] += 1
}

END {
	for (k in intervals) {
		v = intervals[k]
		n = N[k]
		print k OFS v/n
	}
}
' | sort -k3n
