#!/usr/bin/env bash
#
# Prints the number of filenames changed per weekday per author.
#
# <weekday> <author_first_name> <author_last_name> <filenames_changed>

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to print filename changes:
renames="${root}/tools/git/scripts/filename_changes"

# * `renames`
#   - Print filename changes.
# * `awk '{}'`
#   - Tabulate the weekday totals.
"${renames}" | awk '
{
	lines[$1,$6,$7] += 1
}
END {
	for (k in lines) {
		split(k, keys, SUBSEP)
		day = keys[1]
		name = keys[2] OFS keys[3]
		if (day == "Mon") {
			mon[name] = lines[k]
		} else if (day == "Tue") {
			tue[name] = lines[k]
		} else if (day == "Wed") {
			wed[name] = lines[k]
		} else if (day == "Thu") {
			thu[name] = lines[k]
		} else if (day == "Fri") {
			fri[name] = lines[k]
		} else if (day == "Sat") {
			sat[name] = lines[k]
		} else if (day == "Sun") {
			sun[name] = lines[k]
		}
	}
	for (name in mon) {
		print "Mon" OFS name OFS mon[name]
	}
	for (name in tue) {
		print "Tue" OFS name OFS tue[name]
	}
	for (name in wed) {
		print "Wed" OFS name OFS wed[name]
	}
	for (name in thu) {
		print "Thu" OFS name OFS thu[name]
	}
	for (name in fri) {
		print "Fri" OFS name OFS fri[name]
	}
	for (name in sat) {
		print "Sat" OFS name OFS sat[name]
	}
	for (name in sun) {
		print "Sun" OFS name OFS sun[name]
	}
}'
