#!/usr/bin/env bash
#
# @license Apache-2.0
#
# Copyright (c) 2017 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Prints the approximate number of packages per year per author.
#
# <year> <author_first_name> <author_last_name> <num_pkgs>

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to find when `package.json` files were added and deleted:
pkg_json="${root}/tools/git/scripts/pkg_json_added_deleted"

# * `pkg_json`
#   - `package.json` additions and deletions.
# * `awk '{}'`
#   - Tabulate the yearly totals.
# * `sort -k1n`
#   - Sort the year numerically.
# * `awk '{}'`
#   - Format the output.
"${pkg_json}" | awk '
{
	yr = $5
}

# Added a `package.json`:
$8 == "A" {
	pkgs[yr,$6,$7] += 1
}

# Deleted a `package.json`:
$8 == "D" {
	pkgs[yr,$6,$7] -= 1
}

END {
	for (k in pkgs) {
		split(k, keys, SUBSEP)
		print keys[1] OFS keys[2] OFS keys[3] OFS pkgs[k]
	}
}
' | sort -k1n | awk '{print $1 OFS $2 OFS $3 OFS $4}'
