#!/usr/bin/env bash
#
# Prints the number of commits per hour per author.
#
# <hour> <author_first_name> <author_last_name> <number_of_commits>

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to generate commit short stats:
shortstats="${root}/tools/git/scripts/shortstats"

# * `shortstats`
#   - Get summary statistics for each commit.
# * `awk '{}'`
#   - Tabulate the hourly totals.
# * `sort -k1n -k4nr`
#   - Sort the hours in numeric order and sort the totals in reverse numeric order.
"${shortstats}" | awk '
{
	split($4, time, ":")
	hr = time[1]
	lines[hr,$6,$7] += 1
}
END {
	for (k in lines) {
		split(k, keys, SUBSEP)
		print keys[1] OFS keys[2] OFS keys[3] OFS lines[k]
	}
}
' | sort -k1n -k4nr
