#!/usr/bin/env bash
#
# Prints the approximate number of library packages per year per author.
#
# <year> <author_first_name> <author_last_name> <num_pkgs>

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to find when `package.json` files were added and deleted:
pkg_json="${root}/tools/git/scripts/pkg_json_added_deleted"

# * `pkg_json`
#   - `package.json` additions and deletions.
# * `awk '{}'`
#   - Tabulate the yearly totals.
# * `sort -k1n`
#   - Sort the year numerically.
# * `awk '{}'`
#   - Format the output.
"${pkg_json}" | awk '
{
	yr = $5
}

# Skip non-library `package.json`:
$9 !~ /lib\/node_modules\/\@stdlib\// {
	next
}

# Added a `package.json`:
$8 == "A" {
	pkgs[yr,$6,$7] += 1
}

# Deleted a `package.json`:
$8 == "D" {
	pkgs[yr,$6,$7] -= 1
}

END {
	for (k in pkgs) {
		split(k, keys, SUBSEP)
		print keys[1] OFS keys[2] OFS keys[3] OFS pkgs[k]
	}
}
' | sort -k1n | awk '{print $1 OFS $2 OFS $3 OFS $4}'
