#!/usr/bin/env bash
#
# @license Apache-2.0
#
# Copyright (c) 2017 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Prints author commit intervals (in seconds).
#
# <interval> <author_first_name> <author_last_name>
#
# References:
#
# -   Kolassa, Carsten, Dirk Riehle, and Michel A. Salim. 2013. "The Empirical Commit Frequency Distribution of Open Source Projects." In _Proceedings of the 9th International Symposium on Open Collaboration_, 18:1–:8. WikiSym '13. New York, NY, USA: ACM. doi:[10.1145/2491055.2491073](http://dx.doi.org/10.1145/2491055.2491073).

# * `git log`
#   - Show the commit timestamp and author for each commit.
# * `sort -n`
#   - Sort in numeric order.
# * `awk '{}'`
#   - Compute the interval since the last commit,
git log --format=format:"%at %aN" --reverse | sort -n | awk '
{
	ts = $1
	first = $2
	if (NF == 2) {
		last = "(null)"
	} else {
		last = $3
	}
	key = first OFS last
	if (key in prev) {
		print (ts - prev[key]) OFS key
		prev[key] = ts
	} else {
		prev[key] = ts
	}
}
'
