#!/usr/bin/env bash
#
# @license Apache-2.0
#
# Copyright (c) 2017 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Prints the number of authors per year.
#
# <year> <number_of_authors>

# * `git log`
#   - Show logs.
# * `awk '{}'`
#   - Compute number of authors per year.
# * `sort -n`
#   - Sort in numerical order.
git log --format=format:"%ad %aN" --date=format:"%Y" --use-mailmap | awk '
{
	name = $2 $3
	key = $1 SUBSEP name
	if (key in lines) {
		next
	}
	lines[$1,name] = 1
	counts[$1] += 1
}

END {
	for (yr in counts) {
		print yr OFS counts[yr]
	}
}
'  | sort -n
