#!/usr/bin/env bash
#
# Prints the number of deletions per day per author
#
# <month> <day> <year> <author_first_name> <author_last_name> <deletions>.

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to generate commit short stats:
shortstats="${root}/tools/git/scripts/shortstats"

# * `shortstats`
#   - Get summary statistics for each commit.
# * `awk '{}'`
#   - Tabulate the daily totals.
# * `sort -k1n -k2M`
#   - Sort the year numerically and sort the second key as a month.
# * `awk '{}'`
#   - Format the output.
"${shortstats}" | awk '
{
	day = $5 OFS $2 OFS $3

	# Update daily totals per author:
	lines[day,$6,$7] += $10
}
END {
	for (k in lines) {
		split(k, keys, SUBSEP)
		print keys[1] OFS keys[2] OFS keys[3] OFS lines[k]
	}
}
' | sort -k1n -k2M | awk '{print $2 OFS $3 OFS $1 OFS $4 OFS $5 OFS $6}'
