#!/usr/bin/env bash
#
# @license Apache-2.0
#
# Copyright (c) 2017 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Prints the summary statistics per year per author.
#
# <year> <author_first_name> <author_last_name> <num_commits> <files_changed> <additions> <deletions>

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to generate commit short stats:
shortstats="${root}/tools/git/scripts/shortstats"

# * `shortstats`
#   - Get summary statistics for each commit.
# * `awk '{}'`
#   - Tabulate the yearly totals.
# * `sort -k1n`
#   - Sort the year numerically.
"${shortstats}" | awk '
{
	# Update yearly totals per author:
	commits[$5,$6,$7] += 1
	files[$5,$6,$7] += $8
	additions[$5,$6,$7] += $9
	deletions[$5,$6,$7] += $10
}
END {
	for (k in commits) {
		split(k, keys, SUBSEP)
		print keys[1] OFS keys[2] OFS keys[3] OFS commits[k] OFS files[k] OFS additions[k] OFS deletions[k]
	}
}
' | sort -k1n
