#!/usr/bin/env bash
#
# Prints the number of bytes in a package.
#
# <package_path> <number_of_bytes>

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to list packages:
find_pkgs="${root}/tools/scripts/find_packages"

# Define the path to a utility to list files:
find_files="${root}/tools/scripts/find_files"

# Get a list of packages:
pkgs="$(PACKAGES_FILTER=${PACKAGES_FILTER} ${find_pkgs})"

# For each package, determine the number of bytes...
for pkg in ${pkgs}; do
	# * `find_files`
	#   - Find package files.
	# * `ls -l`
	#   - Print file info, which includes number of bytes.
	# * `awk '{}'`
	#   - Compute statistics and print results.
	FILES_PATTERN="${FILES_PATTERN}" FILES_FILTER="$pkg/.*" "${find_files}" | xargs ls -l | awk -v pkg="$pkg" '
{
	bytes += $5 # number of bytes
}

END {
	print pkg OFS bytes
}'
done
