#!/usr/bin/env bash
#
# @license Apache-2.0
#
# Copyright (c) 2017 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Prints the number of bytes in a package.
#
# <package_path> <number_of_bytes>

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to list packages:
find_pkgs="${root}/tools/scripts/find_packages"

# Define the path to a utility to list files:
find_files="${root}/tools/scripts/find_files"

# Get a list of packages:
pkgs="$(PACKAGES_FILTER=${PACKAGES_FILTER} ${find_pkgs})"

# For each package, determine the number of bytes...
for pkg in ${pkgs}; do
	# * `find_files`
	#   - Find package files.
	# * `ls -l`
	#   - Print file info, which includes number of bytes.
	# * `awk '{}'`
	#   - Compute statistics and print results.
	FILES_PATTERN="${FILES_PATTERN}" FILES_FILTER="$pkg/.*" "${find_files}" | xargs ls -l | awk -v pkg="$pkg" '
{
	bytes += $5 # number of bytes
}

END {
	print pkg OFS bytes
}'
done
