#!/usr/bin/env bash
#
# Tabulates commit sizes based on their classification.
#
# References:
#
# * Arafat, Oliver, and Dirk Riehle. 2009. "The Commit Size Distribution of Open Source Software." In *Proceedings of the 42nd Hawaii International Conference on System Sciences*. IEEE Computer Society.
# * Hattori, Lile P., and Michele Lanza. 2008. "On the nature of commits." In *ASE Workshops 2008. 23rd IEEE/ACM International Conference on Automated Software Engineering - Workshops, 2008.* IEEE. doi:[10.1109/ASEW.2008.4686322](http://dx.doi.org/10.1109/ASEW.2008.4686322).

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to compute commit sizes:
commit_sizes="${root}/tools/git/scripts/commit_sizes"

# * `commit_sizes`
#   - Get commit sizes.
# * `awk '{}'`
#   - Classify sizes.
# * `sort -n`
#   - Sort in numeric order.
"${commit_sizes}" | awk '
$1 < 5 {
	table["tiny"] += 1
	next
}

$1 < 20 {
	table["small"] += 1
	next
}

$1 < 200 {
	table["medium"] += 1
	next
}

$1 < 10000 {
	table["large"] += 1
	next
}

# Everything else...
{
	table["huge"] += 1
}

END {
	for (row in table) {
		print row OFS table[row]
	}
}
' | sort -k2nr
