#!/usr/bin/env bash
#
# @license Apache-2.0
#
# Copyright (c) 2017 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Classifies commits based on the number of files changed and prints a classification summary.
#
# References:
#
# -   Hattori, Lile P., and Michele Lanza. 2008. "On the nature of commits." In _ASE Workshops 2008. 23rd IEEE/ACM International Conference on Automated Software Engineering - Workshops, 2008._ IEEE. doi:[10.1109/ASEW.2008.4686322](http://dx.doi.org/10.1109/ASEW.2008.4686322).

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to generate commit short stats:
shortstats="${root}/tools/git/scripts/shortstats"

# * `shortstats`
#   - Get summary statistics for each commit.
# * `awk '{}'`
#   - Classify sizes.
# * `sort -k2nr`
#   - Sort in numeric order.
"${shortstats}" | awk '
# Bug fixes, refactorings...
$8 < 5 {
	table["tiny"] += 1
	next
}

# Adding a new package...
$8 < 25 {
	table["small"] += 1
	next
}

# Large refactorings...
$8 < 125 {
	table["medium"] += 1
	next
}

# Everything else...
{
	table["large"] += 1
}

END {
	for (row in table) {
		print row OFS table[row]
	}
}
' | sort -k2nr
