#!/usr/bin/env bash
#
# Prints the number of commits per month.
#
# <month> <year> <num_commits>

# * `git log`
#   - Show commit logs.
# * `grep '^Date'`
#   - Extract the line which begins with `Date` from each log.
# * `awk '{}'`
#   - From each date line, extract the month (`$3`) and year (`$6`).
# * `sort -k1n -k2M`
#   - Sort the year numerically and sort the second key as a month.
# * `uniq -c`
#   - Remove repeated lines and count the repeats to show monthly totals.
# * `awk '{}'`
#   - Format the output.
git log | grep '^Date' | awk '{print $6 OFS $3}' | sort -k1n -k2M | uniq -c | awk '{print $3 OFS $2 OFS $1}'
