#!/usr/bin/env bash
#
# Prints the number of commits per weekday.
#
# <weekday> <num_commits>

# * `git log`
#   - Show commit logs.
# * `grep '^Date'`
#   - Extract the line which begins with `Date` from each log.
# * `awk '{}'`
#   - From each date line, extract the weekday (`$2`).
# * `sort`
#   - Sort in lexicographic order.
# * `uniq -c`
#   - Remove repeated lines and count the repeats to show weekday totals.
# * `awk '{}'`
#   - Sort the weekdays from Monday to Sunday.
git log | grep '^Date' | awk '{print $2}' | sort | uniq -c | awk '
BEGIN {
	split("Mon Tue Wed Thu Fri Sat Sun", days);
}
{
	lines[$2] = $2 OFS $1
}
END {
	for (i = 1; i <= 7; i++) {
		print lines[days[i]]
	}
}
'
