#!/usr/bin/env bash
#
# @license Apache-2.0
#
# Copyright (c) 2017 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Computes a commit interval histogram.
#
# References:
#
# -   Kolassa, Carsten, Dirk Riehle, and Michel A. Salim. 2013. "The Empirical Commit Frequency Distribution of Open Source Projects." In _Proceedings of the 9th International Symposium on Open Collaboration_, 18:1–:8. WikiSym '13. New York, NY, USA: ACM. doi:[10.1145/2491055.2491073](http://dx.doi.org/10.1145/2491055.2491073).

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to compute commit intervals:
commit_intervals="${root}/tools/git/scripts/commit_intervals"

# * `commit_intervals`
#   - Get commit intervals (in seconds).
# * `awk '{}'`
#   - Generate histogram.
# * `sort -n`
#   - Sort in numeric order.
"${commit_intervals}" | awk '
BEGIN {
	hr = 60 * 60
}

{
	# Round interval to nearest hour:
	bin = int($0/hr + 0.5)
	hist[bin] += 1
}

END {
	for (bin in hist) {
		print bin OFS hist[bin]
	}
}
' | sort -n
