#!/usr/bin/env bash
#
# @license Apache-2.0
#
# Copyright (c) 2017 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Prints the number of commits per month.
#
# <month> <year> <num_commits>

# * `git log`
#   - Show commit logs.
# * `grep '^Date'`
#   - Extract the line which begins with `Date` from each log.
# * `awk '{}'`
#   - From each date line, extract the month (`$3`) and year (`$6`).
# * `sort -k1n -k2M`
#   - Sort the year numerically and sort the second key as a month.
# * `uniq -c`
#   - Remove repeated lines and count the repeats to show monthly totals.
# * `awk '{}'`
#   - Format the output.
git log | grep '^Date' | awk '{print $6 OFS $3}' | sort -k1n -k2M | uniq -c | awk '{print $3 OFS $2 OFS $1}'
