#!/usr/bin/env bash
#
# @license Apache-2.0
#
# Copyright (c) 2017 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Computes a commit size mean.
#
# References:
#
# -   Riehle, Dirk, Carsten Kolassa, and Michel A. Salim. 2012. "Developer Belief vs. Reality: The Case of the Commit Size Distribution." _Software Engineering 2012, GI-Edition Lecture Notes in Informatics_ abs/1408.4644: 59–70. <http://arxiv.org/abs/1408.4644>.

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to compute commit sizes:
commit_sizes="${root}/tools/git/scripts/commit_sizes"

# Define the path to a utility to compute the arithmetic mean:
mean="${root}/tools/awk/mean.awk"

# * `commit_sizes`
#   - Compute commit sizes.
# * `mean`
#   - Compute the mean.
"${commit_sizes}" | "${mean}"
