#!/usr/bin/env bash
#
# Computes the median commit interval (in seconds).
#
# References:
#
# * Kolassa, Carsten, Dirk Riehle, and Michel A. Salim. 2013. "The Empirical Commit Frequency Distribution of Open Source Projects." In *Proceedings of the 9th International Symposium on Open Collaboration*, 18:1–:8. WikiSym '13. New York, NY, USA: ACM. doi:[10.1145/2491055.2491073](http://dx.doi.org/10.1145/2491055.2491073).

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to compute commit intervals:
commit_intervals="${root}/tools/git/scripts/commit_intervals"

# Define the path to a utility to compute the median:
median="${root}/tools/awk/median.awk"

# * `commit_intervals`
#   - Compute commit intervals.
# * `sort -n`
#   - Sort in numeric order.
# * `median`
#   - Compute the median.
"${commit_intervals}" | sort -n | "${median}"
