#!/usr/bin/env bash
#
# @license Apache-2.0
#
# Copyright (c) 2017 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Prints the number of commits per day.
#
# <month> <day> <year> <number_of_commits>

# * `git log --reverse`
#   - Show commit logs in reverse order.
# * `grep '^Date'`
#   - Extract the line which begins with `Date` from each log.
# * `awk '{}'
#   - From each date line, extract the month (`$3`), day (`$4`), and year (`$6`).
# * `sort -k1n -k2M -k3n`
#   - Sort the year numerically, sort the second key as a month, and sort the day numerically.
# * `uniq -c`
#   - Given that same day commits are on consecutive lines, we can remove repeated lines and count the repeats to show daily totals.
# * `awk '{}'`
#   - Format the output.
git log --reverse | grep '^Date' | awk '{print $6 OFS $3 OFS $4}' | sort -k1n -k2M -k3n | uniq -c | awk '{print $3 OFS $4 OFS $2 OFS $1}'
