#!/usr/bin/env bash
#
# Computes a commit size distribution.
#
# References:
#
# * Riehle, Dirk, Carsten Kolassa, and Michel A. Salim. 2012. "Developer Belief vs. Reality: The Case of the Commit Size Distribution." *Software Engineering 2012, GI-Edition Lecture Notes in Informatics* abs/1408.4644: 59–70. <http://arxiv.org/abs/1408.4644>.

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to compute commit sizes:
commit_sizes="${root}/tools/git/scripts/commit_sizes"

# * `commit_sizes`
#   - Get commit sizes.
# * `awk '{}'`
#   - Generate distribution.
# * `sort -n`
#   - Sort in numeric order.
"${commit_sizes}" | awk '
{
	sizes[$1] += 1
}
END {
	for (s in sizes) {
		print s OFS sizes[s]
	}
}
' | sort -n
