#!/usr/bin/env bash
#
# Prints commit intervals (in seconds).
#
# <interval>
#
# References:
#
# * Kolassa, Carsten, Dirk Riehle, and Michel A. Salim. 2013. "The Empirical Commit Frequency Distribution of Open Source Projects." In *Proceedings of the 9th International Symposium on Open Collaboration*, 18:1–:8. WikiSym '13. New York, NY, USA: ACM. doi:[10.1145/2491055.2491073](http://dx.doi.org/10.1145/2491055.2491073).

# * `git log`
#   - Show the commit timestamp for each commit.
# * `awk '{}'`
#   - Compute the interval since the last commit,
git log --format=format:"%at" --reverse | awk '
NR == 1 {
	prev = $0
	next
}

{
	print $0 - prev
	prev = $0
}
'
