#!/usr/bin/env bash
#
# Prints the number of filenames changed per month.
#
# <month> <year> <filenames_changed>

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to print filename changes:
renames="${root}/tools/git/scripts/filename_changes"

# * `renames`
#   - Print filename changes.
# * `awk '{}'`
#   - Tabulate the monthly totals.
# * `sort -k1n -k2M`
#   - Sort the year numerically and sort the second key as a month.
# * `awk '{}'`
#   - Format the output.
"${renames}" | awk '
{
	mon = $5 OFS $2
	lines[mon] += 1
}
END {
	for (mon in lines) {
		print mon OFS lines[mon]
	}
}' | sort -k1n -k2M | awk '{print $2 OFS $1 OFS $3}'
