#!/usr/bin/env bash
#
# @license Apache-2.0
#
# Copyright (c) 2017 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Prints the number of filenames changed per month.
#
# <month> <year> <filenames_changed>

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to print filename changes:
renames="${root}/tools/git/scripts/filename_changes"

# * `renames`
#   - Print filename changes.
# * `awk '{}'`
#   - Tabulate the monthly totals.
# * `sort -k1n -k2M`
#   - Sort the year numerically and sort the second key as a month.
# * `awk '{}'`
#   - Format the output.
"${renames}" | awk '
{
	mon = $5 OFS $2
	lines[mon] += 1
}
END {
	for (mon in lines) {
		print mon OFS lines[mon]
	}
}' | sort -k1n -k2M | awk '{print $2 OFS $1 OFS $3}'
