#!/usr/bin/env bash
#
# Prints a frequency table of number of additions per commit.

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to generate a frequency table:
frequency_table="${root}/tools/awk/frequency_table.awk"

# Define the path to a utility to generate commit short stats:
shortstats="${root}/tools/git/scripts/shortstats"

# Generate shortstats, extract the `additions` column, generate a frequency table, and sort in numeric order:
"${shortstats}" | awk '{print $9}' | "${frequency_table}" | sort -n
