#!/usr/bin/env bash
#
# Prints a frequency table of total commits per day.

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to generate a frequency table:
frequency_table="${root}/tools/awk/frequency_table.awk"

# * `git log`
#   - Show commit logs.
# * `grep Date`
#   - Extract the line which begins with `Date` from each log.
# * `awk '{}'`
#   - From each date line, extract the month (`$3`), day (`$4`), and year (`$6`).
# * `uniq -c`
#   - Given that same day commits are on consecutive lines, we can remove repeated lines and count the repeats to compute daily totals.
# * `awk '{}'`
#   - Extract the total from each line.
# * `awk '{}'`
#   - Generate a frequency table.
git log | grep Date | awk '{print $3 OFS $4 OFS $6}' | uniq -c | awk '{print $1}' | "${frequency_table}" | sort -n

# FIXME: does not include days in which no commits are made!
