#!/usr/bin/env bash
#
# @license Apache-2.0
#
# Copyright (c) 2017 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Prints the number of lines in a file.
#
# <file_type> <number_of_lines> <file_path>
#
# Notes:
#
# -   Results should NOT be confused with source lines of code (SLOC). This implementation measures absolute file length.

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to annotate a file statistic stream:
annotate_file_type="${root}/tools/git/scripts/annotate_file_type.awk"

# * `git ls-files`
#   - List indexed files.
# * `xargs wc -l`
#   - Compute the number of lines within each file.
# * `awk '{}'`
#   - Extract `count` and `filename` columns.
# * `annotate_file_type`
#   - Prefix each result with a file type.
git ls-files | xargs wc -l | awk '
$2 ~ /^total$/ {
	next
}
{
	print $1 OFS $2
}
' | awk -f "${annotate_file_type}"
