#!/usr/bin/env bash
#
# Prints the number of lines in a file.
#
# <file_type> <number_of_lines> <file_path>
#
# Notes:
#
# * Results should NOT be confused with source lines of code (SLOC). This implementation measures absolute file length.

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to annotate a file statistic stream:
annotate_file_type="${root}/tools/git/scripts/annotate_file_type.awk"

# * `git ls-files`
#   - List indexed files.
# * `xargs wc -l`
#   - Compute the number of lines within each file.
# * `awk '{}'`
#   - Extract `count` and `filename` columns.
# * `annotate_file_type`
#   - Prefix each result with a file type.
git ls-files | xargs wc -l | awk '
$2 ~ /^total$/ {
	next
}
{
	print $1 OFS $2
}
' | awk -f "${annotate_file_type}"
