#!/usr/bin/env bash
#
# Prints the number of lines in a package.
#
# <package_path> <number_of_lines>
#
# Notes:
#
# * Results should NOT be confused with source lines of code (SLOC). This implementation measures absolute file length.

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to list packages:
find_pkgs="${root}/tools/scripts/find_packages"

# Define the path to a utility to list files:
find_files="${root}/tools/scripts/find_files"

# Get a list of packages:
pkgs="$(PACKAGES_PATTERN=${PACKAGES_PATTERN} PACKAGES_FILTER=${PACKAGES_FILTER} ${find_pkgs})"

# For each package, determine the number of lines...
for pkg in ${pkgs}; do
	# * `find_files`
	#   - Find package files.
	# * `xargs wc -l`
	#   - Compute the number of lines within each file.
	# * `awk '{}'`
	#   - Extract the total number of lines.
	FILES_PATTERN="${FILES_PATTERN}" FILES_FILTER="$pkg/.*" "${find_files}" | xargs wc -l | awk -v pkg="$pkg" '
$2 ~ /^total$/ {
	print pkg OFS $1
}
{
	next
}
'
done
