#!/usr/bin/env bash
#
# Prints an approximate number of lines per file type.
#
# <proportion> <total_lines> <number_of_files> <average_length> <file_type>
#
# Notes:
#
# * Results should NOT be confused with source lines of code (SLOC). This implementation measures absolute file length.
# * `README.md` files are included in Markdown statistics.

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to compute the number of lines per file:
lines_per_file="${root}/tools/git/scripts/lines_per_file"

# * `lines_per_file`
#   - Compute the number of lines within each file.
# * `awk '{}'`
#   - Compute statistics.
# * `sort -nr`
#   - Sort in reverse numeric order.
"${lines_per_file}" | awk '
$3 ~ /README\.md$/ {
	lines["README"] += $2
	N["README"] += 1
}
{
	lines[$1] += $2
	N[$1] += 1

	lines["total"] += $2
	N["total"] += 1
}

END {
	total = lines["total"]
	for (k in lines) {
		len = lines[k];
		n = N[k]
		pct = int(len/total*10000)/10000
		mu = int(len/n*10000)/10000
		print pct OFS len OFS n OFS mu OFS k
	}
}
' | sort -nr
