#!/usr/bin/env bash
#
# @license Apache-2.0
#
# Copyright (c) 2017 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# List contributors for a provided package.
#
# <commits> <author_firstname> <author_lastname>
#
# This script is called with the following arguments:
#
# * `$1` - package name
#
# Notes:
#
# -   If provided the package name of a namespace, the commit counts include commits for all packages in child directories.
# -   The script only supports packages in the main library (i.e., `lib/node_modules/@stdlib/...` => `@stdlib/math/base/special/pow`).

# VARIABLES #

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to list contributors for a given directory:
list_dir_contributors="${root}/tools/git/scripts/list_dir_contributors"

# Define the package path:
pkg="${root}/lib/node_modules/$1"


# MAIN #

if [[ -d "${pkg}" ]]; then
	"${list_dir_contributors}" "${pkg}"
else
	echo "ERROR: Package does not exist." >&2
	exit 1
fi
