#!/usr/bin/env bash
#
# @license Apache-2.0
#
# Copyright (c) 2017 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Prints the average commit message length per hour.
#
# <hour> <avg_length>

# * `git log`
#   - Print commit messages.
# * `awk '{}'`
#   - Compute hourly averages.
# * `sort -n`
#   - Sort in numerical order.
git log --format=format:"%ad %s" --date=format:"%T" | awk '
{
	split($1, time, ":")
	hr = time[1]
	sum[hr] += length($0) - 9 # "HH:MM:SS "
	N[hr] += 1
}
END {
	for (hr in sum) {
		print hr OFS sum[hr]/N[hr]
	}
}
' | sort -n
