#!/usr/bin/env bash
#
# @license Apache-2.0
#
# Copyright (c) 2017 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Prints the median number of commits per day.

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to compute the median:
median="${root}/tools/awk/median.awk"

# * `git log`
#   - Show commit logs.
# * `grep Date`
#   - Extract the line which begins with `Date` from each log.
# * `awk '{}'`
#   - From each date line, extract the month (`$3`), day (`$4`), and year (`$6`).
# * `uniq -c`
#   - Given that same day commits are on consecutive lines, we can remove repeated lines and count the repeats to compute daily totals.
# * `awk '{}'`
#   - Extract the total from each line.
# * `awk '{}'`
#   - Compute the median number of commits per day.
git log | grep Date | awk '{print $3 OFS $4 OFS $6}' | uniq -c | awk '{print $1}' | "${median}"

# FIXME: does not include days in which no commits are made!
