#!/usr/bin/env bash
#
# Prints the median number of commits per day.

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to compute the median:
median="${root}/tools/awk/median.awk"

# * `git log`
#   - Show commit logs.
# * `grep Date`
#   - Extract the line which begins with `Date` from each log.
# * `awk '{}'`
#   - From each date line, extract the month (`$3`), day (`$4`), and year (`$6`).
# * `uniq -c`
#   - Given that same day commits are on consecutive lines, we can remove repeated lines and count the repeats to compute daily totals.
# * `awk '{}'`
#   - Extract the total from each line.
# * `awk '{}'`
#   - Compute the median number of commits per day.
git log | grep Date | awk '{print $3 OFS $4 OFS $6}' | uniq -c | awk '{print $1}' | "${median}"
