#!/usr/bin/env bash
#
# @license Apache-2.0
#
# Copyright (c) 2017 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Prints the number of merged pull requests per day.
#
# <month> <day> <year> <number_of_merges>

# * `git log --reverse --merges`
#   - Show commit logs in reverse order.
# * `grep 'Merge pull request #'`
#   - Filter for commit messages which explicitly state that a commit merges a pull request.
# * `awk '{}'
#   - From each commit, extract the month (`$1`), day (`$2`), and year (`$3`).
# * `uniq -c`
#   - Given that same day commits are on consecutive lines, we can remove repeated lines and count the repeats to show daily totals.
# * `awk '{}'`
#   - Format the output.
git log --reverse --merges --format=format:"%ad %s" --date=format:"%b %d %Y" | grep 'Merge pull request #' | awk '{print $3 OFS $1 OFS $2}' | uniq -c | awk '{print $3 OFS $4 OFS $2 OFS $1}'
