#!/usr/bin/env bash
#
# @license Apache-2.0
#
# Copyright (c) 2017 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Prints the number of merges per hour.
#
# <hour> <num_merges>

# * `git log --merges`
#   - Show commit logs.
# * `grep Date`
#   - Extract the line which begins with `Date` from each log.
# * `awk '{}'`
#   - From each date line, extract the hour.
# * `sort -n`
#   - Sort in numerical order.
# * `uniq -c`
#   - Remove repeated lines and count the repeats to show hourly totals.
# * `awk '{}'`
#   - Format the output.
git log --merges | grep Date | awk '
{
	split($5, time, ":")
	print time[1]
}
' | sort -n | uniq -c | awk '{print $2 OFS $1}'
