#!/usr/bin/env bash
#
# Prints the number of merged pull requests per hour.
#
# <hour> <num_merges>

# * `git log --merges`
#   - Show commit logs.
# * `grep 'Merge pull request #'`
#   - Filter for commit messages which explicitly state that a commit merges a pull request.
# * `awk '{}'`
#   - From each commit, extract the hour.
# * `sort -n`
#   - Sort in numerical order.
# * `uniq -c`
#   - Remove repeated lines and count the repeats to show hourly totals.
# * `awk '{}'`
#   - Format the output.
git log --merges --format=format:"%ad %s" --date=format:"%T" | grep 'Merge pull request #' | awk '
{
	split($1, time, ":")
	print time[1]
}
' | sort -n | uniq -c | awk '{print $2 OFS $1}'
