#!/usr/bin/env bash
#
# Prints the most frequent number of deletions per commit.

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to compute the mode:
mode="${root}/tools/awk/mode.awk"

# Define the path to a utility to generate commit short stats:
shortstats="${root}/tools/git/scripts/shortstats"

# Generate shortstats, extract the `deletions` column, and compute the mode:
"${shortstats}" | awk '{print $10}' | "${mode}"
