#!/usr/bin/env bash
#
# Prints the number of nonempty lines in a package.
#
# <package_path> <number_of_lines>
#
# Notes:
#
# * Results should NOT be confused with source lines of code (SLOC). This implementation measures only the number of nonempty lines.

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to list packages:
find_pkgs="${root}/tools/scripts/find_packages"

# Define the path to a utility to list files:
find_files="${root}/tools/scripts/find_files"

# Get a list of packages:
pkgs="$(PACKAGES_FILTER=${PACKAGES_FILTER} ${find_pkgs})"

# For each package, determine the number of nonempty lines...
for pkg in ${pkgs}; do
	# * `find_files`
	#   - Find package files.
	# * `xargs grep -c -v '^$'`
	#   - Count the number of nonempty lines within each file.
	# * `sed 's//\2 \1/'`
	#   - Split on the file name and count separator and reverse the arguments.
	# * `awk '{}'`
	#   - Extract the total number of lines.
	FILES_PATTERN="${FILES_PATTERN}" FILES_FILTER="$pkg/.*" "${find_files}" | xargs grep -c -v '^$' | sed 's/\(.*\):\([0-9]\{1,\}\)/\2 \1/' | awk -v pkg="$pkg" '
{
	sum += $1
}

END {
	print pkg OFS sum
}
'
done
