#!/usr/bin/env bash
#
# Prints the number of files in a package.
#
# <package_path> <number_of_files>

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to list packages:
find_pkgs="${root}/tools/scripts/find_packages"

# Define the path to a utility to list files:
find_files="${root}/tools/scripts/find_files"

# Get a list of packages:
pkgs="$(PACKAGES_FILTER=${PACKAGES_FILTER} ${find_pkgs})"

# For each package, determine the number of files...
for pkg in ${pkgs}; do
	# * `find_files`
	#   - Find package files.
	# * `wc -l`
	#   - Compute the number of lines.
	# * `awk '{}'`
	#   - Print results.
	FILES_PATTERN="${FILES_PATTERN}" FILES_FILTER="$pkg/.*" "${find_files}" | wc -l | awk -v pkg="$pkg" '{ print pkg OFS $1 }'
done
