#!/usr/bin/env bash
#
# @license Apache-2.0
#
# Copyright (c) 2017 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Prints `package.json` additions and deletions.
#
# <weekday> <month> <day> <time> <year> <author_first_name> <author_last_name> <action> <filename>

# * `git -c diff.renameLimit=DDDD`
#   - Set the rename limit to a suitably high limit in order to avoid warnings.
# * `log --reverse`
#   - Show commit logs in reverse order.
# * `--find-renames`
#   - Find file renames.
# * `--name-status`
#   - Show only names.
# * `--diff-filter AD`
#   - Only select files which are either added (A) or deleted (D).
# * `--format=format:""`
#   - Format the log.
# * `--date=format:""`
#   - Format the date.
# * `awk '{}'
#   - Process each commit.
git -c diff.renameLimit=2000 log \
	--reverse \
	--find-renames \
	--name-status \
	--diff-filter AD \
	--format=format:"%ad %aN" \
	--date=format:"%a %b %d %T %Y" \
| awk '
# Skip empty lines:
NF == 0 {
	next
}

# Date lines:
! /^[AD]/ {
	date = $0
	next
}

# Skip files which are not `package.json` files:
! /package\.json/ {
	next
}

# Process `package.json` files:
{
	print date OFS $1 OFS $2
}
'
