#!/usr/bin/env bash
#
# @license Apache-2.0
#
# Copyright (c) 2017 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Prints the approximate number of packages per weekday.
#
# <weekday> <num_pkgs>

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to find when `package.json` files were added and deleted:
pkg_json="${root}/tools/git/scripts/pkg_json_added_deleted"

# * `pkg_json`
#   - `package.json` additions and deletions.
# * `awk '{}'`
#   - Tabulate the weekday totals.
"${pkg_json}" | awk '
BEGIN {
	split("Mon Tue Wed Thu Fri Sat Sun", days);
}

# Added a `package.json`:
$8 == "A" {
	pkgs[$1] += 1
}

# Deleted a `package.json`:
$8 == "D" {
	pkgs[$1] -= 1
}

END {
	for (i = 1; i <= 7; i++) {
		day = days[i]
		print day OFS pkgs[day]
	}
}'
