#!/usr/bin/env bash
#
# Prints the number of packages per day.
#
# <month> <day> <year> <num_pkgs>

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to find when `package.json` files were added and deleted:
pkg_json="${root}/tools/git/scripts/pkg_json_added_deleted"

# * `pkg_json`
#   - `package.json` additions and deletions.
# * `awk '{}'`
#   - Tabulate the daily totals.
# * `sort -k1n -k2M`
#   - Sort the year numerically and sort the second key as a month.
# * `awk '{}'`
#   - Format the output.
"${pkg_json}" | awk '
{
	day = $5 OFS $2 OFS $3
}

# Added a `package.json`:
$8 == "A" {
	pkgs[day] += 1
}

# Deleted a `package.json`:
$8 == "D" {
	pkgs[day] -= 1
}

END {
	for (day in pkgs) {
		print day OFS pkgs[day]
	}
}
' | sort -k1n -k2M | awk '{print $2 OFS $3 OFS $1 OFS $4}'
