#!/usr/bin/env bash
#
# @license Apache-2.0
#
# Copyright (c) 2017 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Extracts the first word from each commit message and ranks each word by frequency.
#
# <count> <word>

# * `git log --pretty=format:'%s'`
#   - Show the commit message for each commit
# * `awk '{}'`
#   - Extract first word.
# * `awk '{}'`
#   - Remove commits which use sed syntax.
# * `tr A-Z a-z`
#   - Convert each word to lowercase.
# * `sort`
#   - Sort in lexicographic order.
# * `uniq -c`
#   - Count repeated lines and then remove repeats.
# * `sort -nr`
#   - Sort in reverse numeric order.
git log --pretty=format:'%s' | awk '
/^revert/ {
	print $3
	next
}
/^([A-Za-z0-9]+)(\([A-Za-z0-9]*\))?:/ {
	print $2
	next
}
{
	print $1
}
' | awk '
! /^s\/.+\/.+\/$/ {
	print $0
}
' | tr A-Z a-z | sort | uniq -c | sort -nr
