#!/usr/bin/env bash
#
# Prints summary statistics for each hour.
#
# <hour> <files_changed> <additions> <deletions>

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to generate commit short stats:
shortstats="${root}/tools/git/scripts/shortstats"

# * `shortstats`
#   - Get summary statistics for each commit.
# * `awk '{}'`
#   - Tabulate the hourly totals.
# * `sort -n`
#   - Sort in numerical order.
"${shortstats}" | awk '
{
	split($4, time, ":")
	hr = time[1]

	files[hr] += $8
	additions[hr] += $9
	deletions[hr] += $10
}
END {
	for (hr in files) {
		print hr OFS files[hr] OFS additions[hr] OFS deletions[hr]
	}
}
' | sort -n
