#!/usr/bin/env bash
#
# Prints summary statistics for each month.

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to generate commit short stats:
shortstats="${root}/tools/git/scripts/shortstats"

# * `shortstats`
#   - Get summary statistics for each commit.
# * `awk '{}'`
#   - Extract the commit timestamp and statistics.
# * `perl -pe ''`
#   - Convert each Unix timestamp to a date string.
# * `awk '{}'`
#   - Tabulate the monthly totals.
# * `sort -M`
#   - Sort by month name.
"${shortstats}" | awk '{print $1 OFS $4 OFS $5 OFS $6}' | perl -pe 's/(\d+)/gmtime($1)/e' | awk '
{
	files[$2] += $6
	additions[$2] += $7
	deletions[$2] += $8
}
END {
	for (mon in files) {
		print mon OFS files[mon] OFS additions[mon] OFS deletions[mon]
	}
}' | sort -M
