#!/usr/bin/env bash
#
# Prints summary statistics for each weekday.

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to generate commit short stats:
shortstats="${root}/tools/git/scripts/shortstats"

# * `shortstats`
#   - Get summary statistics for each commit.
# * `awk '{}'`
#   - Extract the commit timestamp and statistics.
# * `perl -pe ''`
#   - Convert each Unix timestamp to a date string.
# * `awk '{}'`
#   - Tabulate the weekday totals.
"${shortstats}" | awk '{print $1 OFS $4 OFS $5 OFS $6}' | perl -pe 's/(\d+)/gmtime($1)/e' | awk '
BEGIN {
	split("Mon Tue Wed Thu Fri Sat Sun", days);
}
{
	files[$1] += $6
	additions[$1] += $7
	deletions[$1] += $8
}
END {
	for ( i = 1; i <= 7; i++ ) {
		day = days[i]
		print day OFS files[day] OFS additions[day] OFS deletions[day]
	}
}'
