#!/usr/bin/env bash
#
# Prints summary statistics for each month.
#
# <month> <year> <files_changed> <additions> <deletions>

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to generate commit short stats:
shortstats="${root}/tools/git/scripts/shortstats"

# * `shortstats`
#   - Get summary statistics for each commit.
# * `awk '{}'`
#   - Tabulate the monthly totals.
# * `sort -k1n -k2M`
#   - Sort the year numerically and sort the second key as a month.
# * `awk '{}'`
#   - Format the output.
"${shortstats}" | awk '
{
	mon = $5 OFS $2

	# Update monthly totals:
	files[mon] += $8
	additions[mon] += $9
	deletions[mon] += $10
}
END {
	for (mon in files) {
		print mon OFS files[mon] OFS additions[mon] OFS deletions[mon]
	}
}
' | sort -k1n -k2M | awk '{print $2 OFS $1 OFS $3 OFS $4 OFS $5}'
