#!/usr/bin/env bash
#
# Prints summary statistics for each weekday.
#
# <weekday> <files_changed> <additions> <deletions>

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to generate commit short stats:
shortstats="${root}/tools/git/scripts/shortstats"

# * `shortstats`
#   - Get summary statistics for each commit.
# * `awk '{}'`
#   - Tabulate the weekday totals.
"${shortstats}" | awk '
BEGIN {
	split("Mon Tue Wed Thu Fri Sat Sun", days);
}
{
	files[$1] += $8
	additions[$1] += $9
	deletions[$1] += $10
}
END {
	for (i = 1; i <= 7; i++) {
		day = days[i]
		print day OFS files[day] OFS additions[day] OFS deletions[day]
	}
}'
