#!/usr/bin/env bash
#
# @license Apache-2.0
#
# Copyright (c) 2017 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Prints the sample standard deviation of deletions per commit.

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to generate commit short stats:
shortstats="${root}/tools/git/scripts/shortstats"

# Define the path to a utility to compute a sample standard deviation:
stdev="${root}/tools/awk/stdev.awk"

# * `shortstats`
#   - Get summary statistics for each commit.
# * `awk '{}'`
#   - Extract the `deletions` column.
# * `stdev`
#   - Compute sample standard deviation.
"${shortstats}" | awk '{print $10}' | "${stdev}"
