#!/usr/bin/env bash
#
# @license Apache-2.0
#
# Copyright (c) 2017 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Prints a frequency table of number of commits per day.

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to generate a frequency table:
tabulate="${root}/tools/awk/tabulate.awk"

# Define the path to a utility to compute the number of commits per day:
commits_per_day="${root}/tools/git/scripts/commits_per_day"

# Compute commits per day, extract the counts column, generate a frequency table, and sort in numeric order:
"${commits_per_day}" | awk '{print $4}' | "${tabulate}" | sort -n

# FIXME: does not account for days with no commits!
