#!/usr/bin/env bash
#
# @license Apache-2.0
#
# Copyright (c) 2017 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Prints a frequency table of number of deletions per commit.

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to generate a frequency table:
tabulate="${root}/tools/awk/tabulate.awk"

# Define the path to a utility to generate commit short stats:
shortstats="${root}/tools/git/scripts/shortstats"

# Generate shortstats, extract the `deletions` column, generate a frequency table, and sort in numeric order:
"${shortstats}" | awk '{print $10}' | "${tabulate}" | sort -n
