#!/usr/bin/env bash
#
# Prints a frequency table of number of files changed per commit.

# Determine root directory:
root="$(git rev-parse --show-toplevel)"

# Define the path to a utility to generate a frequency table:
tabulate="${root}/tools/awk/tabulate.awk"

# Define the path to a utility to generate commit short stats:
shortstats="${root}/tools/git/scripts/shortstats"

# Generate shortstats, extract the `files_changed` column, generate a frequency table, and sort in numeric order:
"${shortstats}" | awk '{print $8}' | "${tabulate}" | sort -n
