#!/usr/bin/env bash
#
# @license Apache-2.0
#
# Copyright (c) 2024 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Script to set up a development environment.

arch="$(uname -m)"

sudo apt-get update

# On ARM64, pin gcc/g++/gfortran to version 12 to avoid a GCC 16 and binutils version mismatch:
if [ "${arch}" = "aarch64" ]; then
	sudo apt-get install -y gfortran-12
	sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 100
	sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 100
	sudo update-alternatives --install /usr/bin/cc cc /usr/bin/gcc-12 100
	sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-12 100
else
	sudo apt-get install -y gfortran
fi

make install
make init

make install-deps-r

# On ARM64, replace the wrong-architecture shellcheck binary with the correct one:
if [ "${arch}" = "aarch64" ]; then
	sc_version="$(shellcheck --version 2>/dev/null | grep '^version:' | awk '{print $2}')"
	if [ -n "${sc_version}" ]; then
		curl -sL "https://github.com/koalaman/shellcheck/releases/download/v${sc_version}/shellcheck-v${sc_version}.linux.aarch64.tar.xz" \
			| sudo tar xJ --strip-components=1 -C /usr/local/bin "shellcheck-v${sc_version}/shellcheck"
	fi
fi
