
# DEPENDENCIES #

include $(TOOLS_MAKE_LIB_DIR)/stats/git.mk
include $(TOOLS_MAKE_LIB_DIR)/stats/npm.mk
include $(TOOLS_MAKE_LIB_DIR)/stats/repl.mk
include $(TOOLS_MAKE_LIB_DIR)/stats/sloc_javascript.mk

