#/
# @license Apache-2.0
#
# Copyright (c) 2018 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#/

# DEPENDENCIES #

# Note: keep in alphabetical order...
include $(TOOLS_MAKE_LIB_DIR)/ls/pkgs/addons.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/pkgs/browser_compatible.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/pkgs/clis.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/pkgs/cmds.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/pkgs/includes.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/pkgs/installed.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/pkgs/lib.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/pkgs/names.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/pkgs/namespace_readmes.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/pkgs/namespaces.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/pkgs/pkgs.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/pkgs/readmes.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/pkgs/repl_help.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/pkgs/standalones.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/pkgs/tools.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/pkgs/toposort.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/pkgs/tree.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/pkgs/types.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/pkgs/unpublished.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/pkgs/wasm.mk
