
# VARIABLES #

# Define a generic filename pattern:
FILES_PATTERN ?= *.*

# Define a generic filepath pattern:
FILES_FILTER ?= .*/.*


# Define a filename pattern for source files:
SOURCES_PATTERN ?= *.js

# Define a filename pattern for C source files:
C_SOURCES_PATTERN ?= *.c

# Define a filename pattern for Fortran source files:
FORTRAN_SOURCES_PATTERN ?= *.f

# Define a filename pattern for Julia source files:
JULIA_SOURCES_PATTERN ?= *.jl

# Define a filename pattern for Python source files:
PYTHON_SOURCES_PATTERN ?= *.py

# Define a filename pattern for R source files:
R_SOURCES_PATTERN ?= *.R

# Define a filepath pattern for source files:
SOURCES_FILTER ?= .*/.*


# Define a filename pattern for test files:
TESTS_PATTERN ?= test*.js

# Define a filepath pattern for test files:
TESTS_FILTER ?= .*/.*


# Define a filename pattern for test fixtures:
TESTS_FIXTURES_PATTERN ?= *.*

# Define a filename pattern for C test fixtures:
C_TESTS_FIXTURES_PATTERN ?= *.c

# Define a filename pattern for Julia test fixtures:
JULIA_TESTS_FIXTURES_PATTERN ?= *.jl

# Define a filename pattern for Python test fixtures:
PYTHON_TESTS_FIXTURES_PATTERN ?= *.py

# Define a filename pattern for R test fixtures:
R_TESTS_FIXTURES_PATTERN ?= *.R

# Define a filepath pattern for test fixture files:
TESTS_FIXTURES_FILTER ?= .*/.*


# Define a filename pattern for benchmark files:
BENCHMARKS_PATTERN ?= benchmark*.js

# Define a filename pattern for C benchmark files:
C_BENCHMARKS_PATTERN ?= benchmark*.c

# Define a filename pattern for Julia benchmark files:
JULIA_BENCHMARKS_PATTERN ?= benchmark*.jl

# Define a filename pattern for Python benchmark files:
PYTHON_BENCHMARKS_PATTERN ?= benchmark*.py

# Define a filename pattern for R benchmark files:
R_BENCHMARKS_PATTERN ?= benchmark*.R

# Define a filepath pattern for benchmark files:
BENCHMARKS_FILTER ?= .*/.*


# Define a filename pattern for example files:
EXAMPLES_PATTERN ?= *.js

# Define a filename pattern for C example files:
C_EXAMPLES_PATTERN ?= *.c

# Define a filename pattern for Julia example files:
JULIA_EXAMPLES_PATTERN ?= *.jl

# Define a filename pattern for Python example files:
PYTHON_EXAMPLES_PATTERN ?= *.py

# Define a filename pattern for R example files:
R_EXAMPLES_PATTERN ?= *.R

# Define a filepath pattern for example files:
EXAMPLES_FILTER ?= .*/.*


# Define a filename pattern for C files:
C_PATTERN ?= *.c

# Define a filepath pattern for C files:
C_FILTER ?= .*/.*


# Define a filename pattern for Fortran files:
FORTRAN_PATTERN ?= *.f

# Define a filepath pattern for Fortran files:
FORTRAN_FILTER ?= .*/.*


# Define a filename pattern for JavaScript files:
JAVASCRIPT_PATTERN ?= *.js

# Define a filepath pattern for JavaScript files:
JAVASCRIPT_FILTER ?= .*/.*


# Define a filename pattern for Julia files:
JULIA_PATTERN ?= *.jl

# Define a filepath pattern for Julia files:
JULIA_FILTER ?= .*/.*


# Define a filename pattern for Markdown files:
MARKDOWN_PATTERN ?= *.md

# Define a filepath pattern for Markdown files:
MARKDOWN_FILTER ?= .*/.*


# Define a filename pattern for Python files:
PYTHON_PATTERN ?= *.py

# Define a filepath pattern for Python files:
PYTHON_FILTER ?= .*/.*


# Define a filename pattern for R files:
R_PATTERN ?= *.R

# Define a filepath pattern for R files:
R_FILTER ?= .*/.*


# Define a filepath pattern for packages:
PACKAGES_FILTER ?= .*/.*


# DEPENDENCIES #

include $(TOOLS_MAKE_LIB_DIR)/ls/files.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/sources.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/sources_c.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/sources_fortran.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/sources_julia.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/sources_python.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/sources_r.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/tests.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/tests_directories.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/tests_fixtures.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/tests_fixtures_c.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/tests_fixtures_julia.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/tests_fixtures_python.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/tests_fixtures_r.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/tools_tests.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/benchmarks.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/benchmarks_c.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/benchmarks_julia.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/benchmarks_python.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/benchmarks_r.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/examples.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/examples_c.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/examples_julia.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/examples_python.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/examples_r.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/c.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/fortran.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/julia.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/markdown.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/python.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/r.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/pkgs.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/pkgs_addons.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/pkgs_clis.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/pkgs_names.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/pkgs_namespaces.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/pkgs_tree.mk
include $(TOOLS_MAKE_LIB_DIR)/ls/pkgs_installed.mk
