#!/usr/bin/env bash
#
# Build script to run at the end of the AppVeyor test [lifecycle][1].
#
# [1]: https://www.appveyor.com/docs/appveyor-yml/


# VARIABLES #

# Define a file containing log output:
log_file='./var/log/appveyor.log'

# Define the number of lines of logged output to print:
tail_num_lines=4000


# FUNCTIONS #

# Defines an error handler.
on_error() {
	echo 'ERROR: An error was encountered during execution.' >&2
	exit 1
}

# Tails a log file.
#
# $1 - log file to tail
# $2 - number of lines to tail
tail_output() {
   echo "Printing the last $2 lines of log output..." >&2
   tail -"$2" "$1"
}

# Main execution sequence.
main() {
	tail_output "${log_file}" "${tail_num_lines}"
}

# Set an error handler:
trap 'on_error' ERR

# Run in the top-level project directory:
cd $(dirname "$0")/../../..

# Run main:
main
