#!/usr/bin/env bash
#
# @license Apache-2.0
#
# Copyright (c) 2017 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Build script to run at the end of the Circle CI test [lifecycle][1].
#
# [1]: https://circleci.com/docs/configuration/#test


# VARIABLES #

# Define a file containing log output:
log_file='/var/log/circle-ci.log'

# Define the number of lines of logged output to print:
tail_num_lines=5000


# FUNCTIONS #

# Defines an error handler.
on_error() {
	echo 'ERROR: An error was encountered during execution.' >&2
	exit 1
}

# Tails a log file.
#
# $1 - log file to tail
# $2 - number of lines to tail
tail_output() {
   echo "Printing the last $2 lines of log output..." >&2
   tail -"$2" "$1"
}

# Main execution sequence.
main() {
	tail_output "${log_file}" "${tail_num_lines}"
}

# Set an error handler:
trap 'on_error' ERR

# Run main:
main
