#!/usr/bin/env bash
#
# @license Apache-2.0
#
# Copyright (c) 2018 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Build script to log metrics in order to monitor process resource usage over time.

# VARIABLES #

# Define an output file to store metrics:
log_file="${CIRCLE_ARTIFACTS}/process_metrics.txt"

# Define an interval for logging metrics:
interval='1s'


# FUNCTIONS #

# Defines an error handler.
on_error() {
	echo 'ERROR: An error was encountered during execution.' >&2
	exit 1
}

# Polls the system for process metrics.
#
# $1 - poll interval
# $2 - output log file
poll() {
	while true; do
		ps -u ubuntu -eo pid,%cpu,%mem,rss,args,uname -w -w --sort=-%mem >> "$2";
		echo '----------' >> "$2";
		sleep "$1";
	done
}

# Main execution sequence.
main() {
	poll "${interval}" "${log_file}"
}

# Set an error handler:
trap 'on_error' ERR

# Run main:
main
