#/
# @license Apache-2.0
#
# Copyright (c) 2026 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#/

# VARIABLES #

# Define the path to the C doctest CLI:
C_DOCTEST_BIN ?= $(TOOLS_PKGS_DIR)/doctest/c/bin/cli

# Define default include paths for C doctesting:
C_DOCTEST_INCLUDE ?= $(SRC_DIR)

# Define default C compiler for doctesting:
C_DOCTEST_COMPILER ?= gcc

# Define output log file for doctest failures:
C_DOCTEST_FAIL_LOG ?= $(ROOT_DIR)/FAIL_LOG_DOCTEST_DOUNRCE


# RULES #

#/
# Runs C doctests extracted from `@example` annotations in C source files.
#
# ## Notes
#
# -   This rule finds C source files containing `@example` annotations and verifies them by compiling and running them.
# -   This rule is useful when wanting to glob for C source files (e.g., run all C doctests for a particular package).
#
#
# @param {string} [SOURCES_FILTER] - file path pattern (e.g., `.*/math/base/special/abs/.*`)
#
# @example
# make doctest-c
#
# @example
# make doctest-c SOURCES_FILTER=".*/math/base/special/abs/.*"
#/
doctest-c: $(NODE_MODULES)
	$(QUIET) fail_log="$(C_DOCTEST_FAIL_LOG)"; \
	: > "$$fail_log"; \
	fail_marker="$${fail_log}.marker"; \
	rm -f "$$fail_marker"; \
	$(FIND_C_SOURCES_CMD) | grep '^[\/]\|^[a-zA-Z]:[/\]' | grep -v '/_tools/' | xargs grep -l '@example' 2>/dev/null | while read -r file; do \
		echo ""; \
		echo "Running C doctest: $$file"; \
		tmp_log="$${fail_log}.tmp"; \
		status=0; \
		NODE_ENV="$(NODE_ENV_EXAMPLES)" \
		NODE_PATH="$(NODE_PATH_EXAMPLES)" \
		$(NODE) $(C_DOCTEST_BIN) \
			--compiler $(C_DOCTEST_COMPILER) \
			--include $(C_DOCTEST_INCLUDE) \
			"$$file" > "$$tmp_log" 2>&1 || status=$$?; \
		cat "$$tmp_log"; \
		if [ $$status -ne 0 ]; then \
			touch "$$fail_marker"; \
			{ \
				echo "=== $$file ==="; \
				cat "$$tmp_log"; \
				echo ""; \
			} >> "$$fail_log"; \
			echo "Logged failure for $$file to $$fail_log"; \
		fi; \
		rm -f "$$tmp_log"; \
	done; \
	if [ -f "$$fail_marker" ]; then \
		echo ""; \
		echo "C doctest failures were logged to $$fail_log"; \
		rm -f "$$fail_marker"; \
		exit 1; \
	fi; \
	rm -f "$$fail_log"

.PHONY: doctest-c

#/
# Runs C doctests extracted from `@example` annotations in a specified list of C source files.
#
# ## Notes
#
# -   This rule is useful when wanting to run C doctests from a list of C source files generated by some other command (e.g., a list of changed C source files obtained via `git diff`).
#
#
# @param {string} FILES - list of C source file paths
#
# @example
# make doctest-c-files FILES='/foo/src/main.c /bar/src/main.c'
#/
doctest-c-files: $(NODE_MODULES)
	$(QUIET) fail_log="$(C_DOCTEST_FAIL_LOG)"; \
	: > "$$fail_log"; \
	fail_marker="$${fail_log}.marker"; \
	rm -f "$$fail_marker"; \
	for file in $(FILES); do \
		echo ""; \
		echo "Running C doctest: $$file"; \
		tmp_log="$${fail_log}.tmp"; \
		status=0; \
		NODE_ENV="$(NODE_ENV_EXAMPLES)" \
		NODE_PATH="$(NODE_PATH_EXAMPLES)" \
		$(NODE) $(C_DOCTEST_BIN) \
			--compiler $(C_DOCTEST_COMPILER) \
			--include $(C_DOCTEST_INCLUDE) \
			"$$file" > "$$tmp_log" 2>&1 || status=$$?; \
		cat "$$tmp_log"; \
		if [ $$status -ne 0 ]; then \
			touch "$$fail_marker"; \
			{ \
				echo "=== $$file ==="; \
				cat "$$tmp_log"; \
				echo ""; \
			} >> "$$fail_log"; \
			echo "Logged failure for $$file to $$fail_log"; \
		fi; \
		rm -f "$$tmp_log"; \
	done; \
	if [ -f "$$fail_marker" ]; then \
		echo ""; \
		echo "C doctest failures were logged to $$fail_log"; \
		rm -f "$$fail_marker"; \
		exit 1; \
	fi; \
	rm -f "$$fail_log"

.PHONY: doctest-c-files
