#!/usr/bin/env bash
#
# Build script to run continuous integration on [Circle CI][1].
#
# [1]: https://circleci.com


# DEPENDENCIES #

# Source nvm to ensure that the `nvm` command is available:
. /opt/circleci/.nvm/nvm.sh


# VARIABLES #

# Determine the root project directory:
root_dir=$(dirname "$0")/../..
root_dir=$(cd "${root_dir}" && echo $PWD)

# Define a username:
username="${CIRCLE_USERNAME}"

# Get the total number of VMs (parallelism):
total_nodes="${CIRCLE_NODE_TOTAL}"

# Get the VM index:
index="${CIRCLE_NODE_INDEX}"

# Define an output file to store log output:
log_file='/var/log/circle-ci.log'

# Define an output file to store unit test results:
tests_log_dir="${CIRCLE_TEST_REPORTS}/junit"
tests_log_file="${tests_log_dir}/test-results.xml"

# Define the pattern for test filenames:
tests_pattern='test*.js'

# Define the pattern for filtering tests based on their file path:
tests_filter='.*/.*'

# Define the directory path of top-level node module dependencies:
node_modules="${root_dir}/node_modules"

# Define the directory path for build artifacts:
build_dir="${root_dir}/build"

# Define the directory path for reports:
reports_dir="${root_dir}/reports"

# Define the directory for top-level tools:
tools_dir="${root_dir}/tools"

# Define a heartbeat interval to periodically print messages in order to prevent Circle CI from prematurely ending a build due to long running commands:
heartbeat_interval='30s'

# Declare a variable for storing the heartbeat process id:
heartbeat_pid=""

# Define the number of lines of logged output to print upon completion:
tail_num_lines=4000


# FUNCTIONS #

# Defines an error handler.
#
# $1 - error status
on_error() {
	echo 'ERROR: An error was encountered during execution.' >&2
	cleanup
	exit "$1"
}

# Runs clean-up tasks.
cleanup() {
	tail_output "${log_file}" "${tail_num_lines}"
	stop_heartbeat
}

# Starts a heartbeat.
#
# $1 - heartbeat interval
start_heartbeat() {
	echo 'Starting heartbeat...' >&2

	# Create a heartbeat and send to background:
	heartbeat "$1" &

	# Capture the heartbeat pid:
	heartbeat_pid=$!
	echo "Heartbeat pid: ${heartbeat_pid}" >&2
}

# Runs an infinite print loop.
#
# $1 - heartbeat interval
heartbeat() {
	while true; do
		echo "$(date) - heartbeat..." >&2;
		sleep "$1";
	done
}

# Stops the heartbeat print loop.
stop_heartbeat() {
	echo 'Stopping heartbeat...' >&2
	kill "${heartbeat_pid}"
}

# Tails a log file.
#
# $1 - log file to tail
# $2 - number of lines to tail
tail_output() {
   echo "Printing the last $2 lines of log output..." >&2
   tail -"$2" "$1"
}

# Creates a directory.
#
# $1 - directory path
create_dir() {
	mkdir -p "$1"
}

# Creates an output log file.
#
# $1 - log file path
create_log_file() {
	local owner=$(whoami)
	echo "Creating an output log file: $1." >&2
	sudo touch "$1"
	sudo chown "${owner}:${owner}" "$1"
}

# Prints a success message.
print_success() {
	echo 'Success!' >&2
}

# Sets the Node.js version.
#
# $1 - version
node_version() {
	echo "Switching to Node.js version: $1..." >&2
	nvm use "$1"
	if [[ "$?" -ne 0 ]]; then
		echo "Unable to set Node.js version to $1." >&2
		return 1
	fi
	echo "Node.js version set to $1." >&2
	return 0
}

# Remove node modules.
#
# $1 - log file
clean_node() {
	echo 'Removing node module dependencies...' >&2
	make clean-node >> "$1" 2>&1
	if [[ "$?" -ne 0 ]]; then
		echo 'Error when attempting to remove dependencies.' >&2
		return 1
	fi
	echo 'Dependencies successfully removed.' >&2
	return 0
}

# Installs dependencies.
#
# $1 - log file
install() {
	echo 'Installing...' >&2
	make install >> "$1" 2>&1
	if [[ "$?" -ne 0 ]]; then
		echo 'Error occurred during install.' >&2
		return 1
	fi
	echo 'Install successful.' >&2
	return 0
}

# Initializes the Node.js environment.
#
# $1 - Node.js version
# $2 - log file
init() {
	node_version "$1"
	if [[ "$?" -ne 0 ]]; then
		return 1
	fi
	clean_node "$2"
	if [[ "$?" -ne 0 ]]; then
		return 1
	fi
	install "$2"
	if [[ "$?" -ne 0 ]]; then
		return 1
	fi
	return 0
}

# Checks dependencies.
#
# $1 - log file
check_deps() {
	echo 'Checking dependencies...' >&2
	make check-deps >> "$1" 2>&1
	if [[ "$?" -ne 0 ]]; then
		echo 'Dependencies are out-of-date.' >&2
		return 1
	fi
	echo 'Dependencies are up-to-date.' >&2
	return 0
}

# Performs lint tasks.
#
# $1 - log file
lint() {
	echo 'Linting filenames...' >&2
	make lint-filenames >> "$1" 2>&1
	if [[ "$?" -ne 0 ]]; then
		echo 'Linting failed.' >&2
		return 1
	fi
	echo 'Linting passed.' >&2
	return 0
}

# Finds test files.
find_tests() {
	local kernel
	local tests

	kernel=$(uname -s)

	# On Mac OSX, in order to use `|` and other regular expression operators, we need to use enhanced regular expression syntax (-E); see https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man7/re_format.7.html#//apple_ref/doc/man/7/re_format.
	if [[ "${kernel}" = "Darwin" ]]; then
		tests=$(find -E "${root_dir}" -name "${tests_pattern}" -regex "${tests_filter}" -not -path "${root_dir}/.*" -not -path "${node_modules}/*" -not -path "${tools_dir}/*" -not -path "${build_dir}/*" -not -path "${reports_dir}/*")
	else
		tests=$(find "${root_dir}" -regextype posix-extended -name "${tests_pattern}" -regex "${tests_filter}" -not -path "${root_dir}/.*" -not -path "${node_modules}/*" -not -path "${tools_dir}/*" -not -path "${build_dir}/*" -not -path "${reports_dir}/*")
	fi
	echo "${tests}"
}

# Allocates tests based on the node (VM) index.
#
# $1 - total number of nodes
# $2 - node index
allocate_tests() {
	# Keep those tests (rows) where the VM index equals the modulo:
	local tests=$(find_tests | sort | awk "NR % $1 == $2")
	echo "${tests}"
}

# Runs unit tests.
#
# $1 - tests
# $2 - log file
run_tests() {
	echo 'Running tests...' >&2
	make TESTS="$1" test-xunit >> "$2" 2>&1
	if [[ "$?" -ne 0 ]]; then
		echo 'Tests failed.' >&2
		return 1
	fi
	echo 'Tests passed.' >&2
	return 0
}

# Main execution sequence.
main() {
	local TASKS
	local tests
	local task
	local len
	local i


	TASKS=(check_deps lint)
	len="${#TASKS[@]}"

	# Create output log files...
	create_log_file "${log_file}"
	if [[ "$?" -ne 0 ]]; then
		on_error 1
	fi
	create_dir "${tests_log_dir}"
	create_log_file "${tests_log_file}"
	if [[ "$?" -ne 0 ]]; then
		on_error 1
	fi

	# Start the heartbeat:
	start_heartbeat "${heartbeat_interval}"

	# Initialize the Node.js environment:
	init stable "${log_file}"
	if [[ "$?" -ne 0 ]]; then
		on_error 1
	fi

	# Assign nodes (VMs) tasks...
	i="${index}"
	while [[ "${i}" -lt "${len}" ]]; do
		task="${TASKS}[${i}]"
		if [[ "${task}" = "check_deps" ]]; then
			check_deps "${log_file}"
			if [[ "$?" -ne 0 ]]; then
				on_error 1
			fi
		elif [[ "${task}" = "lint" ]]; then
			lint "${log_file}"
			if [[ "$?" -ne 0 ]]; then
				on_error 1
			fi
		fi
		i=$(expr "${i}" + "${len}")
	done

	# Assign nodes (VMs) tests to run...
	tests=$(allocate_tests "${total_nodes}" "${index}")
	run_tests "${tests}" "${tests_log_file}"
	if [[ "$?" -ne 0 ]]; then
		on_error 1
	fi

	print_success
	cleanup
	exit 0
}

# Run main:
main
