
# VARIABLES #

# Define the path to the Istanbul executable:
ISTANBUL ?= $(BIN)/istanbul

# Define the type of report Istanbul should produce:
ISTANBUL_REPORT ?= lcov

# Define the output file path for the HTML report generated by Istanbul:
ISTANBUL_HTML_REPORT_PATH ?= $(COVERAGE_DIR)/lcov-report/index.html

# Define the command-line options to be used when invoking the Istanbul executable:
ISTANBUL_FLAGS ?= --no-default-excludes \
		-x 'node_modules/**' \
		-x 'build/**' \
		-x '**/test/**' \
		-x '**/tests/**' \
		-x 'reports/**' \
		--dir $(COVERAGE_DIR) \
		--report $(ISTANBUL_REPORT)

# Define the Istanbul command to run when generating a test-coverage report:
ISTANBUL_CMD ?= $(ISTANBUL) cover $(ISTANBUL_FLAGS)


# TARGETS #

# Run units and generate a test coverage report.
#
# This target instruments source code using [Istanbul][1], runs unit tests, and outputs a test coverage report.
#
# To install Istanbul:
#     $ npm install istanbul
#
# [1] https://github.com/gotwarlost/istanbul

test-istanbul: node_modules
	NODE_ENV=$(NODE_ENV) \
	NODE_PATH=$(NODE_PATH_TEST) \
	$(ISTANBUL_CMD) $(TEST_RUNNER_BIN) -- $(TEST_RUNNER_FLAGS) $(TESTS)


# View a test coverage report.
#
# This target opens an HTML coverage report in a local web browser.

view-istanbul-report:
	$(OPEN) $(ISTANBUL_HTML_REPORT_PATH)


.PHONY: test-istanbul view-istanbul-report
