#/
# @license Apache-2.0
#
# Copyright (c) 2018 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#/

# VARIABLES #

# Define the command for linting license headers:
LICENSE_HEADER_LINT ?= $(TOOLS_PKGS_DIR)/lint/license-header-file-list/bin/cli

# Define the command flags:
LICENSE_HEADER_LINT_FLAGS ?=


# RULES #

#/
# Lints license headers.
#
# @example
# make lint-license-headers
#/
lint-license-headers:
	echo 'TODO'

.PHONY: lint-license-headers

#/
# Lints license headers for a specified list of files.
#
# ## Notes
#
# -   This rule is useful when wanting to lint a list of files generated by some other command (e.g., a list of changed files obtained via `git diff`).
#
#
# @param {string} FILES - list of file paths
#
# @example
# make lint-license-headers-files FILES='/foo/a.js /bar/b.js'
#/
lint-license-headers-files: $(LICENSE_HEADER_LINT) $(NODE_MODULES)
	$(QUIET) for file in $(FILES); do \
		echo ""; \
		echo "Linting: $$file"; \
		NODE_PATH=$(NODE_PATH) $(NODE) $(LICENSE_HEADER_LINT) $(LICENSE_HEADER_LINT_FLAGS) $$file || exit 1; \
	done

.PHONY: lint-license-headers-files

#/
# Lints license headers in JavaScript files.
#
# @example
# make lint-license-headers-javascript
#/
lint-license-headers-javascript: lint-license-headers-javascript-src lint-license-headers-javascript-tests lint-license-headers-javascript-examples lint-license-headers-javascript-benchmarks

.PHONY: lint-license-headers-javascript

#/
# Lints license headers in JavaScript source files.
#
# @param {string} [SOURCES_FILTER] - file path pattern (e.g., `.*/utils/group-by/.*`)
#
# @example
# make lint-license-headers-javascript-src
#
# @example
# make lint-license-headers-javascript-src SOURCES_FILTER=.*/utils/group-by/.*
#/
lint-license-headers-javascript-src: $(LICENSE_HEADER_LINT) $(NODE_MODULES)
	$(QUIET) NODE_PATH=$(NODE_PATH) $(FIND_SOURCES_CMD) | $(NODE) $(LICENSE_HEADER_LINT) $(LICENSE_HEADER_LINT_FLAGS)

.PHONY: lint-license-headers-javascript-src

#/
# Lints license headers in JavaScript test files.
#
# @param {string} [TESTS_FILTER] - file path pattern (e.g., `.*/utils/group-by/.*`)
#
# @example
# make lint-license-headers-javascript-tests
#
# @example
# make lint-license-headers-javascript-tests TESTS_FILTER=.*/utils/group-by/.*
#/
lint-license-headers-javascript-tests: $(LICENSE_HEADER_LINT) $(NODE_MODULES)
	$(QUIET) NODE_PATH=$(NODE_PATH) $(FIND_TESTS_CMD) | $(NODE) $(LICENSE_HEADER_LINT) $(LICENSE_HEADER_LINT_FLAGS)

.PHONY: lint-license-headers-javascript-tests

#/
# Lints license headers in JavaScript examples files.
#
# @param {string} [EXAMPLES_FILTER] - file path pattern (e.g., `.*/utils/group-by/.*`)
#
# @example
# make lint-license-headers-javascript-examples
#
# @example
# make lint-license-headers-javascript-examples EXAMPLES_FILTER=.*/utils/group-by/.*
#/
lint-license-headers-javascript-examples: $(LICENSE_HEADER_LINT) $(NODE_MODULES)
	$(QUIET) NODE_PATH=$(NODE_PATH) $(FIND_EXAMPLES_CMD) | $(NODE) $(LICENSE_HEADER_LINT) $(LICENSE_HEADER_LINT_FLAGS)

.PHONY: lint-license-headers-javascript-examples

#/
# Lints license headers in JavaScript benchmark files.
#
# @param {string} [BENCHMARKS_FILTER] - file path pattern (e.g., `.*/utils/group-by/.*`)
#
# @example
# make lint-license-headers-javascript-benchmarks
#
# @example
# make lint-license-headers-javascript-benchmarks BENCHMARKS_FILTER=.*/utils/group-by/.*
#/
lint-license-headers-javascript-benchmarks: $(LICENSE_HEADER_LINT) $(NODE_MODULES)
	$(QUIET) NODE_PATH=$(NODE_PATH) $(FIND_BENCHMARKS_CMD) | $(NODE) $(LICENSE_HEADER_LINT) $(LICENSE_HEADER_LINT_FLAGS)

.PHONY: lint-license-headers-javascript-benchmarks
