#/
# @license Apache-2.0
#
# Copyright (c) 2025 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#/

# Workflow name:
name: merge_ready_prs

# Workflow triggers:
on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Dry run (only print PRs to be merged)'
        type: boolean
        default: false

# Workflow jobs:
jobs:

  # Define a job for merging PRs with Ready to Merge label:
  merge:

    # Define a display name:
    name: 'Merge Ready PRs'

    # Define the type of virtual host machine:
    runs-on: ubuntu-latest

    # Define the job's steps:
    steps:

      # Checkout the repository:
      - name: 'Checkout repository'
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      # Import GPG key to sign commits:
      - name: 'Import GPG key to sign commits'
        uses: crazy-max/ghaction-import-gpg@e89d40939c28e39f97cf32126055eeae86ba74ec # v6.3.0
        with:
          gpg_private_key: ${{ secrets.STDLIB_BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.STDLIB_BOT_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      # Merge PRs with Ready to Merge label:
      - name: 'Merge PRs'
        env:
          GH_TOKEN: ${{ secrets.STDLIB_BOT_PAT_REPO_WRITE }}
          GITHUB_TOKEN: ${{ secrets.STDLIB_BOT_PAT_REPO_WRITE }}
        run: |
          if [ "${{ inputs.dry-run }}" == "true" ]; then
            . "$GITHUB_WORKSPACE/.github/workflows/scripts/merge_ready_prs" --dry-run
          else
            . "$GITHUB_WORKSPACE/.github/workflows/scripts/merge_ready_prs"
          fi
