#/
# @license Apache-2.0
#
# Copyright (c) 2022 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#/

# Workflow name:
name: scaffold_package_via_rfc_issue_comment

# Workflow triggers:
on:
  issue_comment:
    types: [created]

# Workflow jobs:
jobs:
  scaffold:

    # Define a display name:
    name: 'Scaffold Package via RFC Issue Comment'

    # Define the type of virtual host machine on which to run the job:
    runs-on: ubuntu-latest

    # Define the sequence of job steps...
    steps:
      # Exit if comment does not contain scaffolding directive:
      - name: 'Exit if comment does not contain scaffolding directive'
        if: ${{ !contains(github.event.comment.body, 'scaffold') }}
        run: |
          echo "Comment does not contain scaffolding directive. Exiting..."
          exit 0

      # Checkout the current branch:
      - uses: actions/checkout@v3
        if: ${{ contains(github.event.comment.body, 'scaffold') }}

      # Run the command to scaffold a package:
      - name: 'Scaffold package'
        if: ${{ contains(github.event.comment.body, 'scaffold') }}
        id: scaffold
        uses: stdlib-js/scaffold-pkg-pr-action@main
        with:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Create a pull request:
      - name: 'Create pull request'
        if: ${{ contains(github.event.comment.body, 'scaffold') }}
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PULL_REQUEST_TOKEN }}
          commit-message: 'feat: add `${{ steps.scaffold.outputs.alias }}`'
          title: Add `${{ steps.scaffold.outputs.alias }}` package
          body: |
            This PR adds the [${{ steps.scaffold.outputs.alias }}](../tree/${{ steps.scaffold.outputs.path }}/${{ steps.scaffold.outputs.dir }}) package.

            ## Notes

            *   :warning: The package was scaffolded using the stdlib bot, which uses AI to generate package content. The generated content is not guaranteed to be correct, and will require manual review and editing. :warning:
          branch: ${{ steps.scaffold.outputs.path }}
