#/
# @license Apache-2.0
#
# Copyright (c) 2024 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#/

# Workflow name:
name: slash_commands

# Workflow triggers:
on:
  issue_comment:
    types: [created, edited]

# Workflow jobs:
jobs:

  # Define a job for checking for required files:
  check_files:

    # Define the conditions under which the job should run:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/stdlib check-files')

    # Run reusable workflow:
    uses: ./.github/workflows/check_required_files.yml
    with:
      pull_request_number: ${{ github.event.issue.number }}
      user: ${{ github.event.comment.user.login }}
    secrets:
      STDLIB_BOT_GITHUB_TOKEN: ${{ secrets.STDLIB_BOT_GITHUB_TOKEN }}

  # Define a job for updating copyright header years:
  update_copyright_years:

    # Define the conditions under which the job should run:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/stdlib update-copyright-years')

    # Run reusable workflow:
    uses: ./.github/workflows/update_pr_copyright_years.yml
    with:
      pull_request_number: ${{ github.event.issue.number }}
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
      STDLIB_BOT_GITHUB_TOKEN: ${{ secrets.STDLIB_BOT_GITHUB_TOKEN }}
      STDLIB_BOT_GPG_PRIVATE_KEY: ${{ secrets.STDLIB_BOT_GPG_PRIVATE_KEY }}
      STDLIB_BOT_GPG_PASSPHRASE: ${{ secrets.STDLIB_BOT_GPG_PASSPHRASE }}
